### ISSUE TITLE
LUA error 

### ISSUE THREAD

**Issue by fluiddd** [jordonwow/bigdebuffs#100]
This LUA error pops up non-stop for me. Any idea how I can fix it?

Interface\AddOns\BigDebuffs\BigDebuffs.lua:1921: attempt to index local 'frame' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\BigDebuffs\BigDebuffs.lua"]:1921: in function `?'
[string "@Interface\AddOns\BigDebuffs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...ffs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?   
[string "@Interface\AddOns\BigDebuffs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ffs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\BigDebuffs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\BigDebuffs\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...AddOns\BigDebuffs\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by quadrotony** [comment]
i have same issue, must uninstall because unplayable

**Comment by furax85** [comment]
the same and trying to have some help like you i tag the same lua error message
