### ISSUE TITLE
BD continues to show arena unit frames after arena ends

### ISSUE THREAD

**Issue by AnthonyGress** [jordonwow/bigdebuffs#162]
I figured out it is BD causing this. I also use ElvUI for nameplates but the "default" unit frames stay present even after arenas and while in arena, there are double unit frames. The ones I set with elvUI and stock looking ones caused by BD

**Comment by ryki32** [comment]
Yes. I can confirm this. Happens to me also,also using elvui. Getting error in bugsacker if it help,can post.
