### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by mjdeans** [jordonwow/bigdebuffs#209]
Message: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1513: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_Bar_3:SetPoint.
Time: Wed Jan 27 20:40:40 2021
Count: 2
Stack: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1513: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_Bar_3:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:1513: in function `SetPosition'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:538: in function `Append'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:812: in function `CreateBar'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:10998: in function `Start'
[string "@Interface\AddOns\DBM-PvP\PvPGeneral.lua"]:593: in function `handler'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:893: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:880>

Locals: (*temporary) = DBT_Bar_3 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "TOP"
(*temporary) = DBT_Bar_3 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "BOTTOM"
(*temporary) = 0
(*temporary) = 0

**Comment by hoaxdream** [comment]
This is dbm not bigdebuffs

**Comment by mjdeans** [comment]
My fault, I posted the wrong error. Sorry about that.
