### ISSUE TITLE
Cooldown count dont show up on ennemies nameplates

### ISSUE THREAD

**Issue by starrboi** [jordonwow/bigdebuffs#260]
Hey, first of all ty for this usefull addon.

![aze](https://user-images.githubusercontent.com/81055027/111888918-354fc800-89e1-11eb-8a3e-468c228c3232.png)

As you can see above, even if cooldown count is available i can't see the number of the cooldown count on the icon above nameplate and i don't understand why. Also i'm using Elvui.

Thanks in advance !

**Comment by domzae** [comment]
Same as #224?
In Interface>Game>ActionBars, check if 'Show Numbers for Cooldowns' is checked!

**Comment by starrboi** [comment]
Thanks a lot !
