### ISSUE TITLE
Defensive Debuff Request - Priest Atonement 

### ISSUE THREAD

**Issue by Bialogs** [jordonwow/bigdebuffs#273]
I can make the PR just want to know which atonement spell is appropriate to use or if an inheritance hierarchy needs to be set up.

https://www.wowhead.com/spell=292010/atonement
https://www.wowhead.com/spell=81751/atonement
https://www.wowhead.com/spell=94472/atonement
https://www.wowhead.com/spell=194384/atonement
https://www.wowhead.com/spell=195178/atonement
https://www.wowhead.com/spell=214206/atonement

Thoughts appreciated.

**Comment by domzae** [comment]
Hey Bialogs, I think adding atonement to the spell list doesn't makes sense, I'll try and explain why:

There are 2 cases, either you are the priest casting atonements or you are not the priest. 

In the latter case, whether or not someone has atonement should never change what you decide to do, displaying atonement is like displaying a paladin's Devotion Aura - it has pretty much 100% uptime and doesn't really tell you anything except that a disc priest is nearby.

Now if you are the priest you definitely want to keep track of your atonements, however BigDebuffs is the wrong addon to use for that. Unit Frames and Nameplates can only display 1 aura, so a lot of the time you won't be able to see your atonement timer. Raid Frames (currently) can only show debuffs, this could change in the future but requires re-writing a large chunk of the addon and is not a simple fix. If you want to enlarge/separate your atonements on Raid Frames I can recommend [Enhanced Raid Frames](https://www.curseforge.com/wow/addons/enhanced-raid-frames)

**Comment by Bialogs** [comment]
@domzae this makes perfect sense. I fall in the second case -- I'll explore a raid frames solution! Really appreciate your in-depth explanation.
