### ISSUE TITLE
Thorns 

### ISSUE THREAD

**Issue by Ryssenx** [jordonwow/bigdebuffs#28]
Thorns does not show in bigdebuffs after 8.2

**Comment by diverge18** [comment]
The spell ID is wrong. It should be 305497.

To fix this yourself. go to C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns\BigDebuffs. Then, open retail.lua and search for thorns. Change the spell ID in brackets to 305497 and restart your game.
