### ISSUE TITLE
Mage / Slow / TBC

### ISSUE THREAD

**Issue by kike0605** [jordonwow/bigdebuffs#291]
Heya there can some 1 help me with problem please 🗡️ 
Any way on my main character mage slow like FB blizz and COC is showing on target frame , but when i play from my mage it dosent show any 1 have same issue ?

**Comment by jordonwow** [comment]
Are you getting any errors? Can you try resetting your profile?

**Comment by kike0605** [comment]
No errors at all , just not showing :( i did reset even deleting addon 5 times :(

**Comment by jordonwow** [comment]
Oh I just reread your initial post, snares aren't currently tracked by BigDebuffs, so it must be another addon showing those.

**Comment by kike0605** [comment]
:O ohhh didnt know lol thanks xD
