### ISSUE TITLE
Addon stopped working in dungeons 

### ISSUE THREAD

**Issue by Kalply** [jordonwow/bigdebuffs#337]
Today the addon randomly stopped empathizing dispelable debuffs in dungeons on my raid frames. Not sure what would cause this as I haven't made any changes to to addon and it was working fine before today.

**Comment by aniketschneider** [comment]
I'm seeing this too (in retail), I think it's related to https://github.com/jordonwow/bigdebuffs/issues/336

**Comment by aniketschneider** [comment]
Since 10.9 I'm no longer seeing this.
