### ISSUE TITLE
Legendary Oath of Elder Druid Throws Lua Error

### ISSUE THREAD

**Issue by Tavail** [jordonwow/bigdebuffs#342]
Message: Interface\FrameXML\CompactUnitFrame.lua:1523: Usage: SpellIsPriorityAura(spellID)
Time: Thu Mar 24 15:39:12 2022
Count: 30
Stack: Interface\FrameXML\CompactUnitFrame.lua:1523: Usage: SpellIsPriorityAura(spellID)
[string "=[C]"]: in function `SpellIsPriorityAura'
[string "@Interface\FrameXML\CompactUnitFrame.lua"]:1523: in function <Interface\FrameXML\CompactUnitFrame.lua:1521>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\BigDebuffs\BigDebuffs.lua"]:1414: in function <Interface\AddOns\BigDebuffs\BigDebuffs.lua:1413>
[string "@Interface\AddOns\BigDebuffs\BigDebuffs.lua"]:1481: in function `func'
[string "@Interface\FrameXML\AuraUtil.lua"]:43: in function <Interface\FrameXML\AuraUtil.lua:38>
[string "@Interface\FrameXML\AuraUtil.lua"]:58: in function `ForEachAura'
[string "@Interface\AddOns\BigDebuffs\BigDebuffs.lua"]:1469: in function <Interface\AddOns\BigDebuffs\BigDebuffs.lua:1448>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAuras'
[string "@Interface\FrameXML\CompactUnitFrame.lua"]:96: in function <Interface\FrameXML\CompactUnitFrame.lua:45>

Locals: (*temporary) = "Oath of the Elder Druid"

**Comment by jordonwow** [comment]
fixed #348
