### ISSUE TITLE
LUA Errors with recent bigdebuffs

### ISSUE THREAD

**Issue by jonomurphy** [jordonwow/bigdebuffs#343]
1069x FrameXML\CompactUnitFrame.lua:1523: Usage: SpellIsPriorityAura(spellID)
[string "=[C]"]: in function `SpellIsPriorityAura'
[string "@FrameXML\CompactUnitFrame.lua"]:1523: in function <FrameXML\CompactUnitFrame.lua:1521>
[string "=(tail call)"]: ?
[string "@BigDebuffs\BigDebuffs-v10.10.lua"]:1414: in function <BigDebuffs\BigDebuffs.lua:1413>
[string "@BigDebuffs\BigDebuffs-v10.10.lua"]:1481: in function `func'
[string "@FrameXML\AuraUtil.lua"]:43: in function <FrameXML\AuraUtil.lua:38>
[string "@FrameXML\AuraUtil.lua"]:58: in function `ForEachAura'
[string "@BigDebuffs\BigDebuffs-v10.10.lua"]:1469: in function <BigDebuffs\BigDebuffs.lua:1448>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAuras'
[string "@FrameXML\CompactUnitFrame.lua"]:96: in function <FrameXML\CompactUnitFrame.lua:45>

**Comment by Morrisseyy** [comment]
Getting the same error, in addition to the addon itself not working. i.e. debuffs not showing in matches.

**Comment by Twoheadedx** [comment]
Same error

**Comment by zixzy** [comment]
fix now

**Comment by mbattersby** [comment]
Problem is 

CompactUnitFrame_Util_IsPriorityDebuff(...)
is now 
CompactUnitFrame_Util_IsPriorityDebuff(spellId)

and

CompactUnitFrame_Util_ShouldDisplayDebuff(...)
is now
CompactUnitFrame_Util_ShouldDisplayDebuff(unitCaster, spellId)

**Comment by mbattersby** [comment]
I have a fix but I haven't had a chance to test, I'll PR when I have if it's not fixed before.

**Comment by baena1129** [comment]
Getting this message with ANY debuff I receive. Had to disable the addon completely, even on the 10.8v

Message: Interface\AddOns\BigDebuffs\BigDebuffs.lua:1470: attempt to call global 'CompactUnitFrame_Util_IsBossAura' (a nil value)
Time: Thu Mar 24 19:28:26 2022
Count: 22
Stack: Interface\AddOns\BigDebuffs\BigDebuffs.lua:1470: attempt to call global 'CompactUnitFrame_Util_IsBossAura' (a nil value)
[string "@Interface\AddOns\BigDebuffs\BigDebuffs.lua"]:1470: in function `func'
[string "@Interface\FrameXML\AuraUtil.lua"]:43: in function <Interface\FrameXML\AuraUtil.lua:38>
[string "@Interface\FrameXML\AuraUtil.lua"]:58: in function `ForEachAura'
[string "@Interface\AddOns\BigDebuffs\BigDebuffs.lua"]:1469: in function <Interface\AddOns\BigDebuffs\BigDebuffs.lua:1448>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAuras'
[string "@Interface\FrameXML\CompactUnitFrame.lua"]:96: in function <Interface\FrameXML\CompactUnitFrame.lua:45>

Locals: (*temporary) = nil
(*temporary) = "Exhaustion"
(*temporary) = 136090
(*temporary) = 0
(*temporary) = nil
(*temporary) = 600
(*temporary) = 178984.996000
(*temporary) = "player"
(*temporary) = false
(*temporary) = false
(*temporary) = 57723
(*temporary) = false
(*temporary) = false
(*temporary) = true
(*temporary) = false
(*temporary) = 1
(*temporary) = "attempt to call global 'CompactUnitFrame_Util_IsBossAura' (a nil value)"
bossDebuffs = nil
index = 1
numUsedDebuffs = 0
frame = CompactRaidFrame1 {
 0 = <userdata>
 debuffFrames = <table> {
 }
 BigDebuffs = <table> {
 }
 maxDispelDebuffs = 3
 inUse = true
 inVehicle = false
 background = CompactRaidFrame1Background {
 }
 powerBar = CompactRaidFrame1PowerBar {
 }
 hasDispelPoison = false
 healthBar = CompactRaidFrame1HealthBar {
 }
 overAbsorbGlow = CompactRaidFrame1OverAbsorbGlow {
 }
 hasDispelDisease = false
 horizTopBorder = CompactRaidFrame1HorizTopBorder {
 }
 vertRightBorder = CompactRaidFrame1VertRightBorder {
 }
 myHealPrediction = CompactRaidFrame1MyHealPrediction {
 }
 aggroHighlight = CompactRaidFrame1AggroHighlight {
 }
 myHealAbsorbRightShadow = CompactRaidFrame1MyHealAbsorbRightShadow {
 }
 overHealAbsorbGlow = CompactRaidFrame1OverHealAbsorbGlow {
 }
 newUnit = true
 hasDispelMagic = false
 hasDispelCurse = false
 selectionHighlight = CompactRaidFrame1SelectionHighlight {
 }
 myHealAbsorbLeftShadow = CompactRaidFrame1MyHealAbsorbLeftShadow {
 }
 totalAbsorbOverlay = CompactRaidFrame1TotalAbsorbOverlay {
 }
 unit = "player"
 unitExists = true
 displayedUnit = "player"
 unusedFunc = <function> defined @Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:46
 updateAllEvent = "GROUP_ROSTER_UPDATE"
 statusText = CompactRaidFrame1StatusText {
 }
 horizDivider = CompactRaidFrame1HorizDivider {
 }
 applyFunc = <function> defined @Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:324
 roleIcon = CompactRaidFrame1RoleIcon {
 }
 menu = <function> defined @Interface\FrameXML\CompactUnitFrame.lua:278
 optionTable = <table> {
 }
 otherHealPrediction = CompactRaidFrame1OtherHealPrediction {
 }
 dispelDebuffFrames = <table> {
 }
 buffFrames = <table> {
 }
 maxDebuffs = 3
 centerStatusIcon = CompactRaidFrame1CenterStatusIcon {
 }
 dropDown = CompactRaidFrame1DropDown {
 }
 myHealAbsorb = CompactRaidFrame1MyHealAbsorb {
 }
 maxBuffs = 3
 vertLeftBorder = CompactRaidFrame1VertLeftBorder {
 }
 horizBottomBorder = CompactRaidFrame1HorizBottomBorder {
 }
 name = CompactRaidFrame1Name {
 }
 readyCheckIcon = CompactRaidFrame1ReadyCheckIcon {
 }
 totalAbsorb = CompactRaidFrame1TotalAbsorb {
 }
}
doneWithDebuffs = false
CompactUnitFrame_Util_IsPriorityDebuff = <function> defined @Interface\AddOns\BigDebuffs\BigDebuffs.lua:1413
priorityDebuffs = nil
displayOnlyDispellableDebuffs = false
nonBossDebuffs = nil

**Comment by Emoosch** [comment]
I have the same issue.

240x FrameXML\CompactUnitFrame.lua:1523: Usage: SpellIsPriorityAura(spellID)
[string "=[C]"]: in function `SpellIsPriorityAura'
[string "@FrameXML\CompactUnitFrame.lua"]:1523: in function <FrameXML\CompactUnitFrame.lua:1521>
[string "=(tail call)"]: ?
[string "@BigDebuffs\BigDebuffs-v10.10.lua"]:1414: in function <BigDebuffs\BigDebuffs.lua:1413>
[string "@BigDebuffs\BigDebuffs-v10.10.lua"]:1481: in function `func'
[string "@FrameXML\AuraUtil.lua"]:43: in function <FrameXML\AuraUtil.lua:38>
[string "@FrameXML\AuraUtil.lua"]:58: in function `ForEachAura'
[string "@BigDebuffs\BigDebuffs-v10.10.lua"]:1469: in function <BigDebuffs\BigDebuffs.lua:1448>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAuras'
[string "@FrameXML\CompactUnitFrame.lua"]:96: in function <FrameXML\CompactUnitFrame.lua:45>

Locals:
(*temporary) = "Benommen"

**Comment by cleanlock** [comment]
BigDebuffs stopped working on my raidframes entirely.. anyone with the same issue?

**Comment by aniketschneider** [comment]
@mbattersby I think this is basically what you described: https://github.com/jordonwow/bigdebuffs/pull/348

**Comment by cleanlock** [comment]
> @mbattersby I think this is basically what you described: #348

Yup, that fixed it!

**Comment by mbattersby** [comment]
> 

Yep that's what I did too.

**Comment by canuh** [comment]
> > 
> 
> Yep that's what I did too.

what did you do to fix it please help

it doesn't work on raid frames i can't see my debuffs

**Comment by mbattersby** [comment]
Applied the changes from
https://github.com/jordonwow/bigdebuffs/pull/348/commits/26269273e55f4b1b7840f680ba9b5360fe8df303
by editing the file.
If you don't know what that all means you'll have to wait  for the bigduffs author to merge the PR and put out a new release.

**Comment by capac99** [comment]
i'm having the same problem and dunno what to do D:

**Comment by mbattersby** [comment]
Alternatively you can download https://github.com/aniketschneider/bigdebuffs/blob/patch-3/BigDebuffs.lua and copy that over the existing file with the same name until the author puts out 10.11.

**Comment by jordonwow** [comment]
fixed #348
