### ISSUE TITLE
Bigdebuffs stopped showing all HoTs for resto druid

### ISSUE THREAD

**Issue by smashingallyson** [jordonwow/bigdebuffs#344]
I updated the addon today, and now zero HoTs show for Resto druid when this addon is enabled with blizzard raid frames. If I disable it and use the blizzard raid frames then 3 HoTs only will show up. 

Please help?

**Comment by newuser25234** [comment]
Buffs/debuffs not appearing on raid frames at all today, both in and out of instances

**Comment by fysickz** [comment]
Similar issue for me. Just playing some arena on my druid and I can't see any hots with the latest version. Had to disable the addon.

**Comment by smashingallyson** [comment]
I went back to the 10.8 release and buffs/debuffs show, but only 3 now and not the 6 (option is checked).

**Comment by fsouzadi1995** [comment]
Same here, I had to rollback to 10.8 but I only see 3 buffs and my raid frames debuffs doesn't show

**Comment by jordonwow** [comment]
fixed #348
