### ISSUE TITLE
doesnt work on raid frames

### ISSUE THREAD

**Issue by canuh** [jordonwow/bigdebuffs#349]
doesn't work on raid frames randomly today, was fine yesterday

doesn't work in arenas or in open world

it's only the raid frame debuffs that's broken not the unit frames or the nameplates

i tried rolling back to previous versions and still doesn't work

for some reason it works for some people but not others

please fix

**Comment by jordonwow** [comment]
fixed #348

**Comment by tokeshlol** [comment]
How did you fix it?

**Comment by jordonwow** [comment]
please update to v10.11
