### ISSUE TITLE
After today's BigDebuffs update: still can't hide debuffs

### ISSUE THREAD

**Issue by Hofflerand2** [jordonwow/bigdebuffs#35]
The "Other Debuffs" slider doesn't do anything. I don't know if any of this is related:

1x ...uffs\Libs\AceGUI-3.0-40\widgets\AceGUIWidget-Slider.lua:104: attempt to perform arithmetic on a nil value
...uffs\Libs\AceGUI-3.0-40\widgets\AceGUIWidget-Slider.lua:104: in function <...uffs\Libs\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:99>

Locals:
frame = <unnamed> {
 0 = <userdata>
 obj = <table> {
 }
}
self = <table> {
 disabled = false
 SetSliderValues = <function> defined @BigDebuffs\Libs\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:178
 parent = <table> {
 }
 step = 0.010000
 OnAcquire = <function> defined @BigDebuffs\Libs\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:128
 alignoffset = 25
 userdata = <table> {
 }
 ispercent = true
 value = 0
 base = <table> {
 }
 label = <unnamed> {
 }
 SetDisabled = <function> defined @BigDebuffs\Libs\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:140
 type = "Slider"
 AceGUIWidgetVersion = 22
 GetValue = <function> defined @BigDebuffs\Libs\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:170
 max = 1
 SetValue = <function> defined @BigDebuffs\Libs\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:162
 hightext = <unnamed> {
 }
 min = 0
 SetIsPercent = <function> defined @BigDebuffs\Libs\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:193
 lowtext = <unnamed> {
 }
 events = <table> {
 }
 editbox = <unnamed> {
 }
 frame = <unnamed> {
 }
 SetLabel = <function> defined @BigDebuffs\Libs\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:174
 slider = <unnamed> {
 }
}
value = "5-"
(*temporary) = nil
(*temporary) = "5-"
(*temporary) = nil
(*temporary) = ""
(*temporary) = "attempt to perform arithmetic on a nil value"
tonumber = <function> defined =[C]:-1
PlaySound = <function> defined =[C]:-1

**Comment by jordonwow** [comment]
Please update to latest version
