### ISSUE TITLE
Reasent 10.10 LUA error on retail after blizz update

### ISSUE THREAD

**Issue by neuvo123** [jordonwow/bigdebuffs#350]
Hi! could we please get the same 10.11 fix for retail thats now for classic and tbc the issue still persist in retail and is the same after blizzard latest update.

Game is spamming fatality with buggrab and no conditions or buffs show on raid frames! Help us in retail aswell please.
 Thank you!

2426x FrameXML\CompactUnitFrame.lua:1523: Usage: SpellIsPriorityAura(spellID)
[string "=[C]"]: in function `SpellIsPriorityAura'
[string "@FrameXML\CompactUnitFrame.lua"]:1523: in function <FrameXML\CompactUnitFrame.lua:1521>
[string "=(tail call)"]: ?
[string "@BigDebuffs\BigDebuffs-v10.10.lua"]:1414: in function <BigDebuffs\BigDebuffs.lua:1413>
[string "@BigDebuffs\BigDebuffs-v10.10.lua"]:1481: in function `func'
[string "@FrameXML\AuraUtil.lua"]:43: in function <FrameXML\AuraUtil.lua:38>
[string "@FrameXML\AuraUtil.lua"]:58: in function `ForEachAura'
[string "@BigDebuffs\BigDebuffs-v10.10.lua"]:1469: in function <BigDebuffs\BigDebuffs.lua:1448>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAuras'
[string "@FrameXML\CompactUnitFrame.lua"]:96: in function <FrameXML\CompactUnitFrame.lua:45>

Locals:
(*temporary) = "Paralysis"

**Comment by jordonwow** [comment]
Hi, see https://www.curseforge.com/wow/addons/bigdebuffs/files/3711340

**Comment by neuvo123** [comment]
all seem to be working again thank u alot!
