### ISSUE TITLE
10.11 "ADDON_ACTION_BLOCKED" lua

### ISSUE THREAD

**Issue by neuvo123** [jordonwow/bigdebuffs#352]
Hi seem to be getting this lua error in arena with 10.11 sometimes during match and sometimes start of new match if playing suffle

2x [ADDON_ACTION_BLOCKED] AddOn 'BigDebuffs' tried to call the protected function 'CompactRaidFrame1:ClearAllPoints()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `ClearAllPoints'
[string "@FrameXML\FlowContainer.lua"]:157: in function `FlowContainer_DoLayout'
[string "@FrameXML\FlowContainer.lua"]:17: in function `FlowContainer_ResumeUpdates'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:185: in function `CompactRaidFrameContainer_LayoutFrames'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:130: in function `CompactRaidFrameContainer_TryUpdate'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:62: in function `CompactRaidFrameContainer_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

**Comment by jordonwow** [comment]
What expansion?

**Comment by neuvo123** [comment]
Hi, Shadowlands retail with 10.11 bigdebuff patch

**Comment by neuvo123** [comment]
still happening with 10.12 retail shadowlands

5x [ADDON_ACTION_BLOCKED] AddOn 'BigDebuffs' tried to call the protected function 'CompactRaidFrame1:ClearAllPoints()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `ClearAllPoints'
[string "@FrameXML\FlowContainer.lua"]:157: in function `FlowContainer_DoLayout'
[string "@FrameXML\FlowContainer.lua"]:17: in function `FlowContainer_ResumeUpdates'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:185: in function `CompactRaidFrameContainer_LayoutFrames'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:130: in function `CompactRaidFrameContainer_TryUpdate'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:62: in function `CompactRaidFrameContainer_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

**Comment by jordonwow** [comment]
Can you try v10.14

**Comment by neuvo123** [comment]
Ye 10.14 got rid of these lua errors but some of the buffs dont show up on raidframes after 10.14 like power infusion dont show on person I give it to on raidframe and I used to have them show so Its weird I think its buging but Im not getting any lua error
