### ISSUE TITLE
Issue in new Raid

### ISSUE THREAD

**Issue by OldWorldRaiders** [jordonwow/bigdebuffs#353]
I zoned into sepulcher of the first ones and get infinitely spammed with this:

231x FrameXML\CompactUnitFrame.lua:1523: Usage: SpellIsPriorityAura(spellID)
[string "=[C]"]: in function `SpellIsPriorityAura'
[string "@FrameXML\CompactUnitFrame.lua"]:1523: in function <FrameXML\CompactUnitFrame.lua:1521>
[string "=(tail call)"]: ?
[string "@BigDebuffs\BigDebuffs-v10.10.lua"]:1414: in function <BigDebuffs\BigDebuffs.lua:1413>
[string "@BigDebuffs\BigDebuffs-v10.10.lua"]:1481: in function `func'
[string "@FrameXML\AuraUtil.lua"]:43: in function <FrameXML\AuraUtil.lua:38>
[string "@FrameXML\AuraUtil.lua"]:58: in function `ForEachAura'
[string "@BigDebuffs\BigDebuffs-v10.10.lua"]:1469: in function <BigDebuffs\BigDebuffs.lua:1448>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAuras'
[string "@FrameXML\CompactUnitFrame.lua"]:328: in function <FrameXML\CompactUnitFrame.lua:307>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAll'
[string "@FrameXML\CompactUnitFrame.lua"]:48: in function <FrameXML\CompactUnitFrame.lua:45>

Locals:
(*temporary) = "Light Stagger"

**Comment by jordonwow** [comment]
Sorry about that, it's fixed in v10.11 (#348)
