### ISSUE TITLE
10.12 CompactUnitFrame.lua error

### ISSUE THREAD

**Issue by neuvo123** [jordonwow/bigdebuffs#356]
Making new topic cos this is affecting latest patch, Im getting the following lua error with latest 10.12 patch playing retail arenas, I see there reads "BigDebuffs-v10.11.lua" I did clean install with the new patch but still getting this error I dont know what to do pls help

29x FrameXML\CompactUnitFrame.lua:1436: attempt to index local 'buffFrame' (a nil value)
[string "@FrameXML\CompactUnitFrame.lua"]:1436: in function `CompactUnitFrame_UtilSetBuff'
[string "@BigDebuffs\BigDebuffs-v10.11.lua"]:1519: in function `func'
[string "@FrameXML\AuraUtil.lua"]:43: in function <FrameXML\AuraUtil.lua:38>
[string "@FrameXML\AuraUtil.lua"]:58: in function `ForEachAura'
[string "@BigDebuffs\BigDebuffs-v10.11.lua"]:1501: in function <BigDebuffs\BigDebuffs.lua:1447>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAuras'
[string "@FrameXML\CompactUnitFrame.lua"]:96: in function <FrameXML\CompactUnitFrame.lua:45>

Locals:
buffFrame = nil
index = 4
name = "Renew"
icon = 135953
count = 0
debuffType = "Magic"
duration = 15
expirationTime = 43453.229000
unitCaster = "player"
canStealOrPurge = false
_ = false
spellId = 139
canApplyAura = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'buffFrame' (a nil value)"

**Comment by neuvo123** [comment]
Hi, dont know if this is related to this or if it helps but also getting this after latest wow update, there is unitframe atleast which bigdebuff does changes

3x FrameXML\UnitFrame.lua:462: Usage: GameTooltip:SetUnit("unit"[, hideStatus])
[string "=[C]"]: in function `SetUnit'
[string "@FrameXML\UnitFrame.lua"]:462: in function `UnitFrame_UpdateTooltip'
[string "@FrameXML\UnitFrame.lua"]:452: in function <FrameXML\UnitFrame.lua:451>

Locals:
(*temporary) = GameTooltip {
 0 = <userdata>
 comparing = false
 SetRecipeReagentItem = <function> defined =[C]:-1
 layoutType = "TooltipDefaultLayout"
 TextLeft1 = GameTooltipTextLeft1 {
 }
 waitingForData = false
 ItemTooltip = <unnamed> {
 }
 SetQuestLogItem = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 __tamedCounts = false
 ClearLines = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 shoppingTooltips = <table> {
 }
 textLeft1Font = "GameTooltipHeaderText"
 NineSlice = <unnamed> {
 }
 textLeft2Font = "GameTooltipText"
 TextRight1 = GameTooltipTextRight1 {
 }
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 TopOverlay = <unnamed> {
 }
 Show = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 updateTooltipTimer = 0.007000
 textRight2Font = "GameTooltipText"
 SetQuestItem = <function> defined =[C]:-1
 SetRecipeResultItem = <function> defined =[C]:-1
}
(*temporary) = nil
(*temporary) = nil

**Comment by neuvo123** [comment]
1x [ADDON_ACTION_BLOCKED] AddOn 'BigDebuffs' tried to call the protected function 'CompactRaidFrame5:SetAttribute()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\CompactUnitFrame.lua"]:169: in function `CompactUnitFrame_SetUnit'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:318: in function `CompactRaidFrameContainer_AddUnitFrame'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:266: in function `CompactRaidFrameContainer_AddPets'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:182: in function `CompactRaidFrameContainer_LayoutFrames'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:130: in function `CompactRaidFrameContainer_TryUpdate'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:62: in function `CompactRaidFrameContainer_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

**Comment by Adrenaliin** [comment]
Similar here:

18930x FrameXML\CompactUnitFrame.lua:1122: Attempt to access forbidden object from code tainted by an AddOn
[string "=[C]"]: in function `Hide'
[string "@FrameXML\CompactUnitFrame.lua"]:1122: in function `CompactUnitFrame_UpdateClassificationIndicator'
[string "@FrameXML\CompactUnitFrame.lua"]:1380: in function <FrameXML\CompactUnitFrame.lua:1374>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAuras'
[string "@FrameXML\CompactUnitFrame.lua"]:96: in function <FrameXML\CompactUnitFrame.lua:45>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}


45x FrameXML\CompactUnitFrame.lua:1523: Usage: SpellIsPriorityAura(spellID)
[string "=[C]"]: in function `SpellIsPriorityAura'
[string "@FrameXML\CompactUnitFrame.lua"]:1523: in function <FrameXML\CompactUnitFrame.lua:1521>
[string "=(tail call)"]: ?
[string "@BigDebuffs\BigDebuffs-v10.10.lua"]:1414: in function <BigDebuffs\BigDebuffs.lua:1413>
[string "@BigDebuffs\BigDebuffs-v10.10.lua"]:1481: in function `func'
[string "@FrameXML\AuraUtil.lua"]:43: in function <FrameXML\AuraUtil.lua:38>
[string "@FrameXML\AuraUtil.lua"]:58: in function `ForEachAura'
[string "@BigDebuffs\BigDebuffs-v10.10.lua"]:1469: in function <BigDebuffs\BigDebuffs.lua:1448>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAuras'
[string "@FrameXML\CompactUnitFrame.lua"]:96: in function <FrameXML\CompactUnitFrame.lua:45>

Locals:
(*temporary) = "Trial of Doubt"


1x [ADDON_ACTION_BLOCKED] AddOn 'BigDebuffs' tried to call the protected function 'CompactRaidFrame2:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\CompactUnitFrame.lua"]:378: in function `CompactUnitFrame_UpdateVisible'
[string "@FrameXML\CompactUnitFrame.lua"]:309: in function <FrameXML\CompactUnitFrame.lua:307>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAll'
[string "@FrameXML\CompactUnitFrame.lua"]:145: in function <FrameXML\CompactUnitFrame.lua:45>

**Comment by neuvo123** [comment]
> Similar here:
> 
> 18930x FrameXML\CompactUnitFrame.lua:1122: Attempt to access forbidden object from code tainted by an AddOn [string "=[C]"]: in function `Hide' [string "@FrameXML\CompactUnitFrame.lua"]:1122: in function `CompactUnitFrame_UpdateClassificationIndicator' [string "@FrameXML\CompactUnitFrame.lua"]:1380: in function <FrameXML\CompactUnitFrame.lua:1374> [string "=[C]"]: in function `CompactUnitFrame_UpdateAuras' [string "@FrameXML\CompactUnitFrame.lua"]:96: in function <FrameXML\CompactUnitFrame.lua:45>
> 
> Locals: (*temporary) = { 0 = }
> 
> 45x FrameXML\CompactUnitFrame.lua:1523: Usage: SpellIsPriorityAura(spellID) [string "=[C]"]: in function `SpellIsPriorityAura' [string "@FrameXML\CompactUnitFrame.lua"]:1523: in function <FrameXML\CompactUnitFrame.lua:1521> [string "=(tail call)"]: ? [string "@BigDebuffs\BigDebuffs-v10.10.lua"]:1414: in function <BigDebuffs\BigDebuffs.lua:1413> [string "@BigDebuffs\BigDebuffs-v10.10.lua"]:1481: in function `func' [string "@FrameXML\AuraUtil.lua"]:43: in function <FrameXML\AuraUtil.lua:38> [string "@FrameXML\AuraUtil.lua"]:58: in function `ForEachAura' [string "@BigDebuffs\BigDebuffs-v10.10.lua"]:1469: in function <BigDebuffs\BigDebuffs.lua:1448> [string "=[C]"]: in function `CompactUnitFrame_UpdateAuras' [string "@FrameXML\CompactUnitFrame.lua"]:96: in function <FrameXML\CompactUnitFrame.lua:45>
> 
> Locals: (*temporary) = "Trial of Doubt"
> 
> 1x [ADDON_ACTION_BLOCKED] AddOn 'BigDebuffs' tried to call the protected function 'CompactRaidFrame2:Show()'. [string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519> [string "=[C]"]: in function `Show' [string "@FrameXML\CompactUnitFrame.lua"]:378: in function `CompactUnitFrame_UpdateVisible' [string "@FrameXML\CompactUnitFrame.lua"]:309: in function <FrameXML\CompactUnitFrame.lua:307> [string "=[C]"]: in function `CompactUnitFrame_UpdateAll' [string "@FrameXML\CompactUnitFrame.lua"]:145: in function <FrameXML\CompactUnitFrame.lua:45>

hi are u using the latest 10.12 also? noticed yours is giving "BigDebuffs-v10.10.lua" i were also wondering about this cos im using 10.12 version but i see lua error of "BigDebuffs-v10.11.lua" on mine

**Comment by jordonwow** [comment]
Please reopen if this still occurs in v10.13
