### ISSUE TITLE
LUA errors on (re)load / constant

### ISSUE THREAD

**Issue by Zyrtx** [jordonwow/bigdebuffs#358]
Hi, I've been getting a bunch of LUA errors with the latest version of the addon (10.14). Some only appear on (re)loading the game and others seem to be re-appearing constantly. Could you please have a look at these? Thanks in advance.

**Error 1 - (re)loading the game**

> Message: Interface\AddOns\BigDebuffs\BigDebuffs.lua:1483: attempt to call field 'ShouldSkipAuraUpdate' (a nil value)
> Time: Sat Mar 26 05:27:52 2022
> Count: 1
> Stack: Interface\AddOns\BigDebuffs\BigDebuffs.lua:1483: attempt to call field 'ShouldSkipAuraUpdate' (a nil value)
> [string "=[C]"]: in function \`ShouldSkipAuraUpdate'
> [string "@Interface\AddOns\BigDebuffs\BigDebuffs.lua"]:1483: in function <Interface\AddOns\BigDebuffs\BigDebuffs.lua:1480>
> [string "=[C]"]: in function \`CompactUnitFrame_UpdateAuras'
> [string "@Interface\FrameXML\CompactUnitFrame.lua"]:326: in function <Interface\FrameXML\CompactUnitFrame.lua:305>
> [string "=[C]"]: in function \`CompactUnitFrame_UpdateAll'
> [string "@Interface\FrameXML\CompactUnitFrame.lua"]:182: in function \`CompactUnitFrame_SetUnit'
> [string "@Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:318: in function \`CompactRaidFrameContainer_AddUnitFrame'
> [string "@Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:254: in function \`CompactRaidFrameContainer_AddPlayers'
> [string "@Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:176: in function \`CompactRaidFrameContainer_LayoutFrames'
> [string "@Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:130: in function \`CompactRaidFrameContainer_TryUpdate'
> [string "@Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:95: in function \`CompactRaidFrameContainer_SetFlowSortFunction'
> [string "@Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameManager.lua"]:422: in function <...mpactRaidFrames\Blizzard_CompactRaidFrameManager.lua:417>
> [string "@Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameManager.lua"]:506: in function \`CompactRaidFrameManager_SetSetting'
> [string "@Interface\AddOns\Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:594: in function \`func'
> [string "@Interface\AddOns\Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:571: in function \`CompactUnitFrameProfiles_ApplyProfile'
> [string "@Interface\AddOns\Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:174: in function \`CompactUnitFrameProfiles_ApplyCurrentSettings'
> [string "@Interface\AddOns\Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:170: in function \`CompactUnitFrameProfiles_ActivateRaidProfile'
> [string "@Interface\AddOns\Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:43: in function \`CompactUnitFrameProfiles_ValidateProfilesLoaded'
> [string "@Interface\AddOns\Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:30: in function <...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:19>

**Error 2 - (re)loading the game**

> Message: Interface\AddOns\BigDebuffs\BigDebuffs.lua:1483: attempt to call field 'ShouldSkipAuraUpdate' (a nil value)
> Time: Sat Mar 26 05:27:52 2022
> Count: 1
> Stack: Interface\AddOns\BigDebuffs\BigDebuffs.lua:1483: attempt to call field 'ShouldSkipAuraUpdate' (a nil value)
> [string "=[C]"]: in function \`ShouldSkipAuraUpdate'
> [string "@Interface\AddOns\BigDebuffs\BigDebuffs.lua"]:1483: in function <Interface\AddOns\BigDebuffs\BigDebuffs.lua:1480>
> [string "=[C]"]: in function \`CompactUnitFrame_UpdateAuras'
> [string "@Interface\FrameXML\CompactUnitFrame.lua"]:326: in function <Interface\FrameXML\CompactUnitFrame.lua:305>
> [string "=[C]"]: in function \`func'
> [string "@Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:325: in function \`applyFunc'
> [string "@Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:121: in function \`CompactRaidFrameContainer_ApplyToFrames'
> [string "@Interface\AddOns\Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:577: in function \`CompactUnitFrameProfiles_ApplyProfile'
> [string "@Interface\AddOns\Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:174: in function \`CompactUnitFrameProfiles_ApplyCurrentSettings'
> [string "@Interface\AddOns\Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:170: in function \`CompactUnitFrameProfiles_ActivateRaidProfile'
> [string "@Interface\AddOns\Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:43: in function \`CompactUnitFrameProfiles_ValidateProfilesLoaded'
> [string "@Interface\AddOns\Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:30: in function <...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:19>

**Error 3 - (re)loading the game**

> Message: Interface\AddOns\BigDebuffs\BigDebuffs.lua:1483: attempt to call field 'ShouldSkipAuraUpdate' (a nil value)
> Time: Sat Mar 26 05:27:52 2022
> Count: 1
> Stack: Interface\AddOns\BigDebuffs\BigDebuffs.lua:1483: attempt to call field 'ShouldSkipAuraUpdate' (a nil value)
> [string "=[C]"]: in function \`ShouldSkipAuraUpdate'
> [string "@Interface\AddOns\BigDebuffs\BigDebuffs.lua"]:1483: in function <Interface\AddOns\BigDebuffs\BigDebuffs.lua:1480>
> [string "=[C]"]: in function \`CompactUnitFrame_UpdateAuras'
> [string "@Interface\FrameXML\CompactUnitFrame.lua"]:326: in function <Interface\FrameXML\CompactUnitFrame.lua:305>
> [string "=[C]"]: in function \`func'
> [string "@Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:325: in function \`applyFunc'
> [string "@Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:121: in function \`CompactRaidFrameContainer_ApplyToFrames'
> [string "@Interface\AddOns\Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:577: in function \`CompactUnitFrameProfiles_ApplyProfile'
> [string "@Interface\AddOns\Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:174: in function \`CompactUnitFrameProfiles_ApplyCurrentSettings'
> [string "@Interface\AddOns\Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:170: in function \`CompactUnitFrameProfiles_ActivateRaidProfile'
> [string "@Interface\AddOns\Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:43: in function \`CompactUnitFrameProfiles_ValidateProfilesLoaded'
> [string "@Interface\AddOns\Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:26: in function <...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:19>

**Error 4 - (re)loading the game**

> Message: Interface\AddOns\BigDebuffs\BigDebuffs.lua:1483: attempt to call field 'ShouldSkipAuraUpdate' (a nil value)
> Time: Sat Mar 26 05:27:58 2022
> Count: 1
> Stack: Interface\AddOns\BigDebuffs\BigDebuffs.lua:1483: attempt to call field 'ShouldSkipAuraUpdate' (a nil value)
> [string "@Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149: in function <...dOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147>
> [string "=[C]"]: in function \`ShouldSkipAuraUpdate'
> [string "@Interface\AddOns\BigDebuffs\BigDebuffs.lua"]:1483: in function <Interface\AddOns\BigDebuffs\BigDebuffs.lua:1480>
> [string "=[C]"]: in function \`CompactUnitFrame_UpdateAuras'
> [string "@Interface\FrameXML\CompactUnitFrame.lua"]:326: in function <Interface\FrameXML\CompactUnitFrame.lua:305>
> [string "=[C]"]: in function \`CompactUnitFrame_UpdateAll'
> [string "@Interface\FrameXML\CompactUnitFrame.lua"]:50: in function <Interface\FrameXML\CompactUnitFrame.lua:45>
> 
> Locals: private = \<table> {
>  ThrowError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:48
>  DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:90
>  ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:110
>  SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:86
>  MAX_STACK_DEPTH = 10
>  log = \<table> {
>  }
>  ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:119
>  IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:80
>  NewError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:52
>  IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:97
> }
> orig_errorhandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355

**Error 5 - constant**

> Message: Interface\AddOns\BigDebuffs\BigDebuffs.lua:1483: attempt to call field 'ShouldSkipAuraUpdate' (a nil value)
> Time: Sat Mar 26 05:37:38 2022
> Count: 94
> Stack: Interface\AddOns\BigDebuffs\BigDebuffs.lua:1483: attempt to call field 'ShouldSkipAuraUpdate' (a nil value)
> [string "@Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149: in function <...dOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147>
> [string "=[C]"]: in function \`ShouldSkipAuraUpdate'
> [string "@Interface\AddOns\BigDebuffs\BigDebuffs.lua"]:1483: in function <Interface\AddOns\BigDebuffs\BigDebuffs.lua:1480>
> [string "=[C]"]: in function \`CompactUnitFrame_UpdateAuras'
> [string "@Interface\FrameXML\CompactUnitFrame.lua"]:94: in function <Interface\FrameXML\CompactUnitFrame.lua:45>
> 
> Locals: private = \<table> {
>  ThrowError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:48
>  DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:90
>  ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:110
>  SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:86
>  MAX_STACK_DEPTH = 10
>  log = \<table> {
>  }
>  ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:119
>  IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:80
>  NewError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:52
>  IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:97
> }
> orig_errorhandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355

**Error 6 - constant**

> Message: Interface\AddOns\BigDebuffs\BigDebuffs.lua:1483: attempt to call field 'ShouldSkipAuraUpdate' (a nil value)
> Time: Sat Mar 26 05:38:54 2022
> Count: 55
> Stack: Interface\AddOns\BigDebuffs\BigDebuffs.lua:1483: attempt to call field 'ShouldSkipAuraUpdate' (a nil value)
> [string "@Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149: in function <...dOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147>
> [string "=[C]"]: in function \`ShouldSkipAuraUpdate'
> [string "@Interface\AddOns\BigDebuffs\BigDebuffs.lua"]:1483: in function <Interface\AddOns\BigDebuffs\BigDebuffs.lua:1480>
> [string "=[C]"]: in function \`CompactUnitFrame_UpdateAuras'
> [string "@Interface\FrameXML\CompactUnitFrame.lua"]:326: in function <Interface\FrameXML\CompactUnitFrame.lua:305>
> [string "=[C]"]: in function \`CompactUnitFrame_UpdateAll'
> [string "@Interface\FrameXML\CompactUnitFrame.lua"]:182: in function \`CompactUnitFrame_SetUnit'
> [string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:417: in function \`OnAdded'
> [string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:118: in function \`OnNamePlateAdded'
> [string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:47>
> 
> Locals: private = \<table> {
>  ThrowError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:48
>  DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:90
>  ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:110
>  SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:86
>  MAX_STACK_DEPTH = 10
>  log = \<table> {
>  }
>  ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:119
>  IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:80
>  NewError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:52
>  IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:97
> }
> orig_errorhandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355

**Error 7 - constant**

> Message: Interface\AddOns\BigDebuffs\BigDebuffs.lua:1483: attempt to call field 'ShouldSkipAuraUpdate' (a nil value)
> Time: Sat Mar 26 05:35:03 2022
> Count: 10
> Stack: Interface\AddOns\BigDebuffs\BigDebuffs.lua:1483: attempt to call field 'ShouldSkipAuraUpdate' (a nil value)
> [string "@Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149: in function <...dOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147>
> [string "=[C]"]: in function \`ShouldSkipAuraUpdate'
> [string "@Interface\AddOns\BigDebuffs\BigDebuffs.lua"]:1483: in function <Interface\AddOns\BigDebuffs\BigDebuffs.lua:1480>
> [string "=[C]"]: in function \`CompactUnitFrame_UpdateAuras'
> [string "@Interface\FrameXML\CompactUnitFrame.lua"]:58: in function <Interface\FrameXML\CompactUnitFrame.lua:45>
> 
> Locals: private = \<table> {
>  ThrowError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:48
>  DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:90
>  ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:110
>  SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:86
>  MAX_STACK_DEPTH = 10
>  log = \<table> {
>  }
>  ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:119
>  IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:80
>  NewError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:52
>  IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:97
> }
> orig_errorhandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355

**Comment by jordonwow** [comment]
What are you doing when this happens? Arena, BG? Do the constant errors being only after a /reload?

**Comment by Zyrtx** [comment]
> What are you doing when this happens? Arena, BG? Do the constant errors begin only after a /reload?

Nothing specific, just standing around in any area with enemy NPC's will trigger these.
The constant errors start immediately after first loading into the game, reloading has no effect on those.

**Comment by jordonwow** [comment]
should be fixed
