### ISSUE TITLE
Friendly buffs disappearing since 9.2

### ISSUE THREAD

**Issue by Dimowx** [jordonwow/bigdebuffs#362]
Date: 2022-03-26 10:03:34
ID: -100
Error occured in: Global
Count: 121
Message: ..\AddOns\BigDebuffs\BigDebuffs.lua line 1371:
   attempt to call global 'CompactUnitFrame_Util_IsBossAura' (a nil value)
Debug:
   [string "@BigDebuffs\BigDebuffs.lua"]:1371: func()
   [string "@..\FrameXML\AuraUtil.lua"]:43:
      ..\FrameXML\AuraUtil.lua:38
   [string "@..\FrameXML\AuraUtil.lua"]:58: ForEachAura()
   [string "@BigDebuffs\BigDebuffs.lua"]:1370:
      BigDebuffs\BigDebuffs.lua:1349
   [string "=[C]"]: CompactUnitFrame_UpdateAuras()
   [string "@..\FrameXML\CompactUnitFrame.lua"]:96:
      ..\FrameXML\CompactUnitFrame.lua:45
Locals:
(*temporary) = nil
(*temporary) = "Knockdown"
(*temporary) = 134060
(*temporary) = 0
(*temporary) = nil
(*temporary) = 1
(*temporary) = 1212109.473000
(*temporary) = "nameplate6"
(*temporary) = false
(*temporary) = false
(*temporary) = 362409
(*temporary) = false
(*temporary) = false
(*temporary) = false
(*temporary) = false
(*temporary) = 1
(*temporary) = "attempt to call global 'CompactUnitFrame_Util_IsBossAura' (a nil value)"
bossDebuffs = nil
index = 1
numUsedDebuffs = 0
frame = CompactPartyFrameMember1 {
 0 = <userdata>
 debuffFrames = <table> {
 }
 BigDebuffs = <table> {
 }
 maxDispelDebuffs = 3
 inVehicle = false
 background = CompactPartyFrameMember1Background {
 }
 powerBar = CompactPartyFrameMember1PowerBar {
 }
 hasDispelPoison = false
 healthBar = CompactPartyFrameMember1HealthBar {
 }
 overAbsorbGlow = CompactPartyFrameMember1OverAbsorbGlow {
 }
 horizTopBorder = CompactPartyFrameMember1HorizTopBorder {
 }
 vertRightBorder = CompactPartyFrameMember1VertRightBorder {
 }
 myHealPrediction = CompactPartyFrameMember1MyHealPrediction {
 }
 aggroHighlight = CompactPartyFrameMember1AggroHighlight {
 }
 myHealAbsorbRightShadow = CompactPartyFrameMember1MyHealAbsorbRightShadow {
 }
 overHealAbsorbGlow = CompactPartyFrameMember1OverHealAbsorbGlow {
 }
 newUnit = true
 updateAllEvent = "GROUP_ROSTER_UPDATE"
 selectionHighlight = CompactPartyFrameMember1SelectionHighlight {
 }
 hasDispelDisease = false
 hasDispelMagic = false
 myHealAbsorbLeftShadow = CompactPartyFrameMember1MyHealAbsorbLeftShadow {
 }
 totalAbsorbOverlay = CompactPartyFrameMember1TotalAbsorbOverlay {
 }
 unit = "player"
 unitExists = true
 hasDispelCurse = false
 statusText = CompactPartyFrameMember1StatusText {
 }
 horizDivider = CompactPartyFrameMember1HorizDivider {
 }
 displayedUnit = "player"
 roleIcon = CompactPartyFrameMember1RoleIcon {
 }
 menu = <function> defined @Interface\FrameXML\CompactUnitFrame.lua:278
 optionTable = <table> {
 }
 otherHealPrediction = CompactPartyFrameMember1OtherHealPrediction {
 }
 dispelDebuffFrames = <table> {
 }
 buffFrames = <table> {
 }
 maxDebuffs = 3
 centerStatusIcon = CompactPartyFrameMember1CenterStatusIcon {
 }
 dropDown = CompactPartyFrameMember1DropDown {
 }
 myHealAbsorb = CompactPartyFrameMember1MyHealAbsorb {
 }
 maxBuffs = 3
 vertLeftBorder = CompactPartyFrameMember1VertLeftBorder {
 }
 horizBottomBorder = CompactPartyFrameMember1HorizBottomBorder {
 }
 name = CompactPartyFrameMember1Name {
 }
 readyCheckIcon = CompactPartyFrameMember1ReadyCheckIcon {
 }
 totalAbsorb = CompactPartyFrameMember1TotalAbsorb {
 }
}
doneWithDebuffs = false
CompactUnitFrame_Util_IsPriorityDebuff = <function> defined @Interface\AddOns\BigDebuffs\BigDebuffs.lua:1314
priorityDebuffs = nil
displayOnlyDispellableDebuffs = false
nonBossDebuffs = nil

AddOns:
  Swatter, v9.1.BETA.5.3 (OneMawTime)
  AdvancedInterfaceOptions, v1.7.0
  AnnoyingPopupRemover, vv13.0.1-release
  ArenaNumbers, v
  Auctioneer, v9.1.BETA.5.3 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.3 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.3 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.3 (OneMawTime)
  BattleGroundEnemies, v9.0.5.6
  BigDebuffs, vv10.7
  Binder, v2.8.2
  CheckPVP, v1.3.0
  CovenantMissionHelper, v3.2.0
  DampeningDisplay, v9.0.2
  DBMCore, v489cf2a
  DBMInterrupts, v8.3.0
  DBMStatusBarTimers, v489cf2a
  DBMVPVEM, v81c3e41
  eAlignUpdated, v9.1.0
  Enchantrix, v9.1.BETA.5.3 (OneMawTime)
  EnchantrixBarker, v9.1.BETA.5.3 (OneMawTime)
  FasterLoot, v2.01
  GatherMate2, v1.47.1
  Gladius, v7.0.7
  GryphonRemover, v1.0
  GryphonsRemover, vv6.0 WoD Beta
  Informant, v9.1.BETA.5.3 (OneMawTime)
  JaxPartyCastbars, vv2.0
  jaxSurrender, vv1.0
  MaxCam, vv2.5.9
  MBB, v4.0.7
  MoveAnything, v18.0.7
  NameplateCooldowns, v90200.0-release
  OmniBar, vv10.9
  OmniCC, v9.0.6-beta1
  OmniCD, v2.6.40
  PartyAbilityBars, v
  Postal, vv3.7.8
  RareScanner, v9.2.0.4
  REFlex, v3.1.7
  SellJunk, v3.0.20
  SilentWorldQuest, v8.2.0
  SilentWorldQuestOptions, v8.2.0
  SimpleClassPortraits, v
  Simulationcraft, v9.2.0
  SlideBar, v9.1.BETA.5.3 (OneMawTime)
  SnowfallKeyPress, v
  SortGroup, v4.2
  Stubby, v9.1.BETA.5.3 (OneMawTime)
  TomTom, vv90001-1.1.7
  WarGameHelper, v1.1.5
  WeakAuras, v3.7.14
  WorldBossTimers, vv1.9.3
  WorldQuestTracker, v
  ZerethMortisPuzzleHelper, v1.5
  BlizRuntimeLib_enUS v9.2.0.90200 <none>
  (ck=625)

**Comment by jordonwow** [comment]
Hi, looks like you're on v10.7. Please update to v10.14
