### ISSUE TITLE
bigdebuffs not showing on raidframes or showing longer than necessary

### ISSUE THREAD

**Issue by revenge66** [jordonwow/bigdebuffs#364]
bigdebuffs isn't showing certain stuns/disarms on raidframes half the time even after updating. also sometimes the cc shows longer than necessary on raidframes on the rare occasion it DOES show.

**Comment by respekten** [comment]
have same issue

**Comment by revenge66** [comment]
![WoWScrnShot_032822_092342](https://user-images.githubusercontent.com/102512529/160407886-2cca1ffc-ef43-40c9-b9cf-31d49a4de546.jpg)

**Comment by revenge66** [comment]
this is an example of it being bugged and showing leg sweep on both of us after it's already faded 3 or 4 seconds ago. it stayed on the feral for at least 20 more seconds after as well. multiple cc's have been doing this when they even show up. sometimes they just don't all together

**Comment by respekten** [comment]
> this is an example of it being bugged and showing leg sweep on both of us after it's already faded 3 or 4 seconds ago. it stayed on the feral for at least 20 more seconds after as well. multiple cc's have been doing this when they even show up. sometimes they just don't all together

i have the same;(

**Comment by okane103** [comment]
+1 experiencing the same issue

**Comment by dextergordonx** [comment]
+1 also experiencing

**Comment by jaketheknights** [comment]
I have this issue

**Comment by jordonwow** [comment]
Please let me know if the latest release resolves this issue

**Comment by okane103** [comment]
> Please let me know if the latest release resolves this issue

It looks like the issue is resolved now, thanks for the quick fix.

**Comment by revenge66** [comment]
> Please let me know if the latest release resolves this issue

just got done doing arena. the addon is back to working properly. thank you jordon
