### ISSUE TITLE
Certain debuffs not showing on raidframes - build 10.14

### ISSUE THREAD

**Issue by dextergordonx** [jordonwow/bigdebuffs#365]
The bug spam has been fixed but certain debuffs are not showing on raidframes, it seems to be debuffs that aren't dispellable, stuns for instance. 

Kidney, leg sweep, etc....

Thanks for all the work.

**Comment by tokeshlol** [comment]
I had similar issues last night.  Worked fine yetserday afternoon then debuffs stopped showing or were showing up in weird positions.  Haven't tried again since last night.

**Comment by respekten** [comment]
same issues

**Comment by jaketheknights** [comment]
+1

**Comment by jordonwow** [comment]
#364
