### ISSUE TITLE
Issue in arena

### ISSUE THREAD

**Issue by markonibomboni** [jordonwow/bigdebuffs#38]
Message: Interface\AddOns\BigDebuffs\BigDebuffs.lua:1138: script ran too long
Time: Sun Sep 29 21:42:54 2019
Count: 1
Stack: Interface\AddOns\BigDebuffs\BigDebuffs.lua:1138: script ran too long
Interface\AddOns\BigDebuffs\BigDebuffs.lua:1138: in function `UNIT_AURA'
Interface\AddOns\BigDebuffs\BigDebuffs.lua:411: in function <Interface\AddOns\BigDebuffs\BigDebuffs.lua:411>

Locals: self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 SaveUnitFramePosition = <function> defined @Interface\AddOns\BigDebuffs\BigDebuffs.lua:507
 EnableModule = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 baseName = "BigDebuffs"
 IterateEmbeds = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 IsDispellable = <function> defined @Interface\AddOns\BigDebuffs\BigDebuffs.lua:738
 SecureHookScript = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceHook-3.0\AceHook-3.0.lua:410
 IsPriorityBigDebuff = <function> defined @Interface\AddOns\BigDebuffs\BigDebuffs.lua:1037
 RawHookScript = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceHook-3.0\AceHook-3.0.lua:395
 PriorityDebuffs = <table> {
 }
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 defaultModuleState = true
 IsEnabled = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 DisableModule = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 RegisterMessage = <function> defined @Interface\AddOns\BigDebuffs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\BigDebuffs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 frames = <table> {
 }
 IsHooked = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceHook-3.0\AceHook-3.0.lua:493
 PLAYER_FOCUS_CHANGED = <function> defined @Interface\AddOns\BigDebuffs\BigDebuffs.lua:1169
 WarningDebuffs = <table> {
 }
 UNIT_AURA = <function> defined @Interface\AddOns\BigDebuffs\BigDebuffs.lua:1043
 SetEnabledState = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 COMBAT_LOG_EVENT_UNFILTERED = <function> defined @Interface\AddOns\BigDebuffs\BigDebuffs.lua:580
 RegisterEvent = <function> defined @Interface\AddOns\BigDebuffs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 units = <table> {
 }
 IterateModules = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:437
 RawHook = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceHook-3.0\AceHook-3.0.lua:313
 AttachUnitFrame = <function> defined @Interface\AddOns\BigDebuffs\BigDebuffs.lua:402
 OnInitialize = <function> defined @Interface\AddOns\BigDebuffs\BigDebuffs.lua:346
 NewModule = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 GetModule = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 AttachedFrames = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 options = <table> {
 }
 specDispel = <table> {
 }
 Spells = <table> {
 }
 GetName = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 UNIT_AURA_ALL_UNITS = <function> defined @Interface\AddOns\BigDebuffs\BigDebuffs.lua:626
 name = "BigDebuffs"
 orderedModules = <table> {
 }
 Disable = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
 ShowInRaids = <function> defined @Interface\AddOns\BigDebuffs\BigDebuffs.lua:1181
 UnitFrames = <table> {
 }
 db = <table> {
 }
 HookScript = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceHook-3.0\AceHook-3.0.lua:366
 SetupOptions = <function> defined @Interface\AddOns\BigDebuffs\Options

**Comment by jordonwow** [comment]
Please upgrade to v8.1
