### ISSUE TITLE
No "Offensive Debuffs" section in config -> Spells

### ISSUE THREAD

**Issue by danielgstamps** [jordonwow/bigdebuffs#408]
What is even the purpose of this addon, if not tracking debuffs?

**Comment by jordonwow** [comment]
# BigDebuffs
BigDebuffs is an _extremely lightweight_ addon that hooks the Blizzard raid frames to increase the debuff size of crowd control effects. Additionally, it replaces unit frame portraits with debuff durations when important debuffs are present.

[Open a ticket to report any issues](https://github.com/jordonwow/bigdebuffs/issues)

[Submit a pull request](https://github.com/jordonwow/bigdebuffs/pulls)

## Features

### Anchor
Anchor BigDebuffs to the inner (default), left, or right of the raid frames.

![BigDebuffs Anchor Inner](http://i.imgur.com/O9Yacnl.png)
![BigDebuffs Anchor Right](http://i.imgur.com/NfADLaw.png)
![BigDebuffs Anchor Left](http://i.imgur.com/gYQ8DEM.png)

### Increase Maximum Buffs
Sets the maximum buffs displayed to 6.

![BigDebuffs Increase Maximum Buffs](http://i.imgur.com/iq5I2E4.png)

### Scale
Set the scale of the various types of debuffs.

### Warning Debuffs
Always show warning debuffs when BigDebuffs are displayed.

![BigDebuffs Special Debuffs](http://i.imgur.com/b0UWslt.png)

### Unit Frames
Show BigDebuffs on the unit frames.

![BigDebuffs Unit Frames](http://i.imgur.com/6QSbDlB.png)

### Third Party Support
BigDebuffs is fully compatible with the followings mods:

*   Z-Perl UnitFrames
*   Shadowed Unit Frames
*   ElvUI
*   Adapt
*   bUnitFrames

![BigDebuffs Z-Perl](http://i.imgur.com/ZOr4tbi.png)

### Profiles
Create custom profiles with dual specialization support.

## Configuration
To open the options panel, type `/bd`
