### ISSUE TITLE
Broken in prepatch

### ISSUE THREAD

**Issue by nonstopjoker** [jordonwow/bigdebuffs#421]
The unitframe icons aren't in the right place, they are in the middle of the screen. I'm also getting around 14 lua errors from BigDebuffs. Any ETA when this will be updated for Dragonflight?

**Comment by Kordiel** [comment]
"The unitframe icons aren't in the right place, they are in the middle of the screen." Same prob for me, can't play with it blocking the screen. Too bad it's a great addon, please fix it, thanks!
