### ISSUE TITLE
Error that doesn't allow BigDebuffs to run

### ISSUE THREAD

**Issue by tickix** [jordonwow/bigdebuffs#46]
Hi, I'm playing classic right now. Currently I get this error. I assume this is because there is something with LibClassicDurations? But I think my classicauradurations also depends on it and that addon is fine. Not sure what is going on.

Message: Interface\AddOns\BigDebuffs\BigDebuffs.lua:8: Cannot find a library instance of "LibClassicDurations".
Time: Thu Dec  5 20:11:15 2019
Count: 1
Stack: Interface\AddOns\BigDebuffs\BigDebuffs.lua:8: Cannot find a library instance of "LibClassicDurations".
[C]: in function `error'
...ace\AddOns\AtlasLootClassic\Libs\LibStub\LibStub.lua:38: in function `LibStub'
Interface\AddOns\BigDebuffs\BigDebuffs.lua:8: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "LibClassicDurations"."

Message: Interface\AddOns\BigDebuffs\Options.lua:35: bad argument #1 to 'pairs' (table expected, got nil)
Time: Thu Dec  5 20:11:15 2019
Count: 1
Stack: Interface\AddOns\BigDebuffs\Options.lua:35: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
Interface\AddOns\BigDebuffs\Options.lua:35: in main chunk

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by jordonwow** [comment]
Please try latest version
