### ISSUE TITLE
Size of buffs

### ISSUE THREAD

**Issue by Jiywa** [jordonwow/bigdebuffs#512]
Ever since the new update. The size of our friendly buffs is significantly smaller. Does anyone know how to make them bigger?

**Comment by eelldlleed** [comment]
Search this self.db.profile.raidFrames.buffs * 0.01 in bigdebuff.lua and change 0.01 to 0.013 or whatever you prefer.

**Comment by Jiywa** [comment]
> Search this self.db.profile.raidFrames.buffs * 0.01 in bigdebuff.lua and change 0.01 to 0.013 or whatever you prefer.

YOU ARE MY HERO
