### ISSUE TITLE
classic bigdebuffs

### ISSUE THREAD

**Issue by bshakex** [jordonwow/bigdebuffs#55]
28x BigDebuffs\Libs\AceEvent-3.0\AceEvent-3.0-4.lua:37: Attempt to unregister unknown event "UPDATE_WORLD_STATES"
[C]: in function `UnregisterEvent'
BigDebuffs\Libs\AceEvent-3.0\AceEvent-3.0-4.lua:37: in function `OnUnused'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:197: in function `UnregisterAllEvents'

**Comment by jordonwow** [comment]
Please update to the latest version
