### ISSUE TITLE
SetPortraitToTexture(): Texture is not 64x64 pixels:

### ISSUE THREAD

**Issue by erxx** [jordonwow/bigdebuffs#58]
1x BigDebuffs\BigDebuffs-v8.7.lua:1488: SetPortraitToTexture(): Texture is not 64x64 pixels: FileData ID 611425.

[string "=[C]"]: in function `SetPortraitToTexture'
[string "@BigDebuffs\BigDebuffs-v8.7.lua"]:1488: in function `UNIT_AURA'
[string "@BigDebuffs\BigDebuffs-v8.7.lua"]:411: in function <BigDebuffs\BigDebuffs.lua:411>

Locals:
(*temporary) = BigDebuffsarena1UnitFrameIcon {
 0 = <userdata>
}
(*temporary) = 611425

**Comment by denumerable** [comment]
Same issue:

Message: Interface\AddOns\BigDebuffs\BigDebuffs.lua:1488: SetPortraitToTexture(): Texture is not 64x64 pixels: FileData ID 611425.

Time: Fri Mar 27 21:31:29 2020
Count: 1
Stack: Interface\AddOns\BigDebuffs\BigDebuffs.lua:1488: SetPortraitToTexture(): Texture is not 64x64 pixels: FileData ID 611425.

[string "=[C]"]: in function `SetPortraitToTexture'
[string "@Interface\AddOns\BigDebuffs\BigDebuffs.lua"]:1488: in function `UNIT_AURA'
[string "@Interface\AddOns\BigDebuffs\BigDebuffs.lua"]:411: in function <Interface\AddOns\BigDebuffs\BigDebuffs.lua:411>

Locals: (*temporary) = BigDebuffstargetUnitFrameIcon {
 0 = <userdata>
}
(*temporary) = 611425

**Comment by butter-nut** [comment]
Having the same error
