### ISSUE TITLE
FPS Stuttering issues related to this

### ISSUE THREAD

**Issue by WuhbGaming** [jordonwow/bigdebuffs#608]
Someone made a post about it, definitely functions BigDebuffs uses

https://us.forums.blizzard.com/en/wow/t/errors-with-ui-scalingresizingframexml/1503981

Any way to circumvent this? Constant reloading on every single arena gets old quickly.

**Comment by F1T1L** [comment]
they fixed it probably. now i dont need reload every damn arena match at start

**Comment by WuhbGaming** [comment]
Still occurs but you can at least almost for sure make it through an entire match(shuffle) now before it becomes unbearable.

**Comment by jordonwow** [comment]
Can you post the lua error you're getting now?

**Comment by eightflat** [comment]
Can you/anyone explain what the fix was? 

When 10.0.5 went live, I was getting horrible horrible FPS drops/freezing. Using debuggers, I also thought BigDebuffs was one of the culprits, but it didn't seem to be only BigDebuffs since the problems persisted even with it disabled.

Not too long after 10.0.5 went live, a ton of addons updated and things seemed to get better, but the problem still seemed to happen, especially right when enemies would come out of stealth in PvP.

Anyway, before the supposed BigDebuffs FPS fix, things just seem to have resolve themselves without disabling any other addons. Not sure if it was another addon update, but I would love to know generally what caused the issue!

**Comment by jordonwow** [comment]
I believe one of the issues was a call to `CompactUnitFrame_SetMaxBuffs`, which directly modifies the frame's `maxBuffs` value, causing taint. Another potential cause was extra/unneeded code in the `CompactUnitFrame_UpdateAuras` hook.

I am unable to produce any taint or errors after this fix, so if any of you are still getting lua errors please post them here.

**Comment by WuhbGaming** [comment]
Left it on as long as I could bear, this is what I could find out:
No errors but still severe and unplayable frames/stutters sometime through the 2nd or 3rd+ shuffle if you don't reload

After turning it off I made it through about 12-13 matches before I noticed hiccups, (but at least playable)

**Comment by WuhbGaming** [comment]
No FPS issues yet just the old racial/castbar stuff that has happened forever.

Racial:

Message: Interface/AddOns/Gladius/Modules/Racial.lua:347: attempt to index field '?' (a nil value)
Time: Sat Feb  4 12:13:57 2023
Count: 4
Stack: Interface/AddOns/Gladius/Modules/Racial.lua:347: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/Gladius/Modules/Racial.lua"]:347: in function `?'
[string "@Interface/AddOns/Gladius/Gladius.lua"]:68: in function `Call'
[string "@Interface/AddOns/Gladius/Gladius.lua"]:777: in function `ShowUnit'
[string "@Interface/AddOns/Gladius/Gladius.lua"]:507: in function `?'
[string "@Interface/AddOns/Gladius/Gladius.lua"]:51: in function <Interface/AddOns/Gladius/Gladius.lua:43>

Locals: self = <table> {
 UpdateRacial = <function> defined @Interface/AddOns/Gladius/Modules/Racial.lua:198
 messages = <table> {
 }
 Enable = <function> defined @Interface/AddOns/Gladius/Gladius.lua:127
 AutoFixAll = <function> defined @Interface/AddOns/Gladius/Modules/Racial.lua:127
 GetRacialCD = <function> defined @Interface/AddOns/Gladius/Modules/Racial.lua:191
 UpdateColors = <function> defined @Interface/AddOns/Gladius/Modules/Racial.lua:240
 CreateFrame = <function> defined @Interface/AddOns/Gladius/Modules/Racial.lua:221
 enabled = true
 UNIT_NAME_UPDATE = <function> defined @Interface/AddOns/Gladius/Modules/Racial.lua:114
 eventHandler = Frame {
 }
 GetOptions = <function> defined @Interface/AddOns/Gladius/Modules/Racial.lua:402
 attachTo = true
 name = "Racial"
 IsEnabled = <function> defined @Interface/AddOns/Gladius/Gladius.lua:143
 Disable = <function> defined @Interface/AddOns/Gladius/Gladius.lua:135
 RegisterMessage = <function> defined @Interface/AddOns/Gladius/Gladius.lua:147
 Update = <function> defined @Interface/AddOns/Gladius/Modules/Racial.lua:244
 isBarOption = false
 templates = <table> {
 }
 SendMessage = <function> defined @Interface/AddOns/Gladius/Gladius.lua:151
 UNIT_AURA = <function> defined @Interface/AddOns/Gladius/Modules/Racial.lua:142
 OnDisable = <function> defined @Interface/AddOns/Gladius/Modules/Racial.lua:95
 GetAttachTo = <function> defined @Interface/AddOns/Gladius/Modules/Racial.lua:102
 OptionsLoad = <function> defined @Interface/AddOns/Gladius/Modules/Racial.lua:391
 RegisterEvent = <function> defined @Interface/AddOns/Gladius/Gladius.lua:112
 IsDetached = <function> defined @Interface/AddOns/Gladius/Modules/Racial.lua:106
 UNIT_SPELLCAST_SUCCEEDED = <function> defined @Interface/AddOns/Gladius/Modules/Racial.lua:159
 defaults = <table> {
 }
 GetFrame = <function> defined @Interface/AddOns/Gladius/Modules/Racial.lua:110
 OnEnable = <function> defined @Interface/AddOns/Gladius/Modules/Racial.lua:85
 UnregisterAllEvents = <function> defined @Interface/AddOns/Gladius/Gladius.lua:123
 Show = <function> defined @Interface/AddOns/Gladius/Modules/Racial.lua:344
 Test = <function> defined @Interface/AddOns/Gladius/Modules/Racial.lua:382
 frame = <table> {
 }
 UnregisterEvent = <function> defined @Interface/AddOns/Gladius/Gladius.lua:119
 Reset = <function> defined @Interface/AddOns/Gladius/Modules/Racial.lua:360
}
unit = "arena5"
testing = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
Gladius = <table> {
 GetColorOption = <function> defined @Interface/AddOns/Gladius/Options.lua:149
 defaults = <table> {
 }
 testCount = 0
 instanceType = "arena"
 OnInitialize = <function> defined @Interface/AddOns/Gladius/Gladius.lua:225
 NewModule = <function> defined @Interface/AddOns/Gladius/Gladius.lua:100
 EnableModule = <function> defined @Interface/AddOns/Gladius/Gladius.lua:196
 modules = <table> {
 }
 GetModule = <function> defined @Interface/AddOns/Gladius/Gladius.lua:210
 ARENA_PREP_OPPONENT_SPECIALIZATIONS = <function> defined @Interface/AddOns/Gladius/Gladius.lua:523
 UpdateColors = <function> defined @Interface/AddOns/Gladius/Gladius.lua:562
 CreateButton = <function> defined @Interface/AddOns/Gladius/Gladius.lua:852


------------------------------------
Castbar:

Message: Interface/AddOns/Gladius/Modules/CastBar.lua:449: attempt to index field '?' (a nil value)
Time: Sat Feb  4 12:17:46 2023
Count: 2
Stack: Interface/AddOns/Gladius/Modules/CastBar.lua:449: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/Gladius/Modules/CastBar.lua"]:449: in function `?'
[string "@Interface/AddOns/Gladius/Gladius.lua"]:68: in function `Call'
[string "@Interface/AddOns/Gladius/Gladius.lua"]:833: in function `ResetUnit'
[string "@Interface/AddOns/Gladius/Gladius.lua"]:569: in function `HideFrame'
[string "@Interface/AddOns/Gladius/Gladius.lua"]:454: in function `LeftArena'
[string "@Interface/AddOns/Gladius/Gladius.lua"]:405: in function `?'
[string "@Interface/AddOns/Gladius/Gladius.lua"]:51: in function <Interface/AddOns/Gladius/Gladius.lua:43>

Locals: self = <table> {
 defaults = <table> {
 }
 messages = <table> {
 }
 Enable = <function> defined @Interface/AddOns/Gladius/Gladius.lua:127
 UnregisterAllEvents = <function> defined @Interface/AddOns/Gladius/Gladius.lua:123
 CastEnd = <function> defined @Interface/AddOns/Gladius/Modules/CastBar.lua:242
 UNIT_SPELLCAST_INTERRUPTIBLE = <function> defined @Interface/AddOns/Gladius/Modules/CastBar.lua:140
 UpdateColors = <function> defined @Interface/AddOns/Gladius/Modules/CastBar.lua:293
 enabled = true
 UNIT_SPELLCAST_NOT_INTERRUPTIBLE = <function> defined @Interface/AddOns/Gladius/Modules/CastBar.lua:154
 eventHandler = Frame {
 }
 GetOptions = <function> defined @Interface/AddOns/Gladius/Modules/CastBar.lua:505
 attachTo = true
 name = "CastBar"
 IsEnabled = <function> defined @Interface/AddOns/Gladius/Gladius.lua:143
 Disable = <function> defined @Interface/AddOns/Gladius/Gladius.lua:135
 RegisterMessage = <function> defined @Interface/AddOns/Gladius/Gladius.lua:147
 Update = <function> defined @Interface/AddOns/Gladius/Modules/CastBar.lua:325
 UNIT_SPELLCAST_DELAYED = <function> defined @Interface/AddOns/Gladius/Modules/CastBar.lua:209
 isBarOption = true
 UNIT_SPELLCAST_STOP = <function> defined @Interface/AddOns/Gladius/Modules/CastBar.lua:202
 GetAttachTo = <function> defined @Interface/AddOns/Gladius/Modules/CastBar.lua:87
 OnDisable = <function> defined @Interface/AddOns/Gladius/Modules/CastBar.lua:80
 isBar = true
 CreateBar = <function> defined @Interface/AddOns/Gladius/Modules/CastBar.lua:253
 GetFrame = <function> defined @Interface/AddOns/Gladius/Modules/CastBar.lua:95
 RegisterEvent = <function> defined @Interface/AddOns/Gladius/Gladius.lua:112
 IsDetached = <function> defined @Interface/AddOns/Gladius/Modules/CastBar.lua:91
 Show = <function> defined @Interface/AddOns/Gladius/Modules/CastBar.lua:442
 UNIT_SPELLCAST_START = <function> defined @Interface/AddOns/Gladius/Modules/CastBar.lua:107
 UNIT_SPELLCAST_CHANNEL_START = <function> defined @Interface/AddOns/Gladius/Modules/CastBar.lua:168
 OnEnable = <function> defined @Interface/AddOns/Gladius/Modules/CastBar.lua:54
 GetIndicatorHeight = <function> defined @Interface/AddOns/Gladius/Modules/CastBar.lua:103
 SendMessage = <function> defined @Interface/AddOns/Gladius/Gladius.lua:151
 Test = <function> defined @Interface/AddOns/Gladius/Modules/CastBar.lua:462
 frame = <table> {
 }
 UnregisterEvent = <function> defined @Interface/AddOns/Gladius/Gladius.lua:119
 Reset = <function> defined @Interface/AddOns/Gladius/Modules/CastBar.lua:447
}
unit = "arena5"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"

**Comment by citna** [comment]
That Gladius version appears out of date and probably missing Dracthyr in the Racial module

**Comment by jordonwow** [comment]
Good to hear, thanks for your help.
