### ISSUE TITLE
Polymorph not handled as "CC"/ wrong size

### ISSUE THREAD

**Issue by lvxku** [jordonwow/bigdebuffs#622]
**Game Version:**
> 10.0.5 live Build 48317

**Description:**
> Despite all of mage's polymorph spell versions being listed under the "Crowd Control" category in options,
> it is currently not being handled as a CC spell and also ignores custom size overrides.

**Reproducible:**
> Yes

**Howto:**
>Have "Dispellable CC","Other CC","Dispellable PvE","Warning Debuffs" at e.g. 100% and "Offensive Debuffs","Other Debuffs" at a smaller, in my case 50%, size

![poly example](https://user-images.githubusercontent.com/125774468/222317675-9ef4ecb4-ab64-4e1d-b9c2-9a4d8c3da91b.png)
![polymorph settings example](https://user-images.githubusercontent.com/125774468/222317693-0753c204-fe5d-4e96-a540-407d053087dd.png)

**Comment by citna** [comment]
Does it do this even without the Mainline file edited? It appears in your screenshot that the children spell IDs for Polymorph were removed from the parent. I don't think a clean install should show each Polymorph spell individually like that

**Comment by lvxku** [comment]
Yea, this happens regardless. Removing the parent attribute and having them handled as individual CCs was just my first attempt at fixing this :(

**Comment by citna** [comment]
I haven't had a chance to see if I can replicate the problem yet. I did try to see if I could notice anything wrong with the spell IDs, typos, or any duplicates and I didn't notice anything so far. I went on Wowhead and noticed that Polymorph has a flag for a Boss Aura. I didn't find this flag for any of the other IDs in the addon I went to check for so this could be doing it since some of the code was edited in the taint issue fix update.

**Comment by lvxku** [comment]
Seems to definitely be a common problem as streamers with a similar bigdebuffs setup have the same issue e.g. Trillebartom:
![image](https://user-images.githubusercontent.com/125774468/223280764-7d796755-58a4-43f0-9880-c195ffa860c2.png)

**Comment by jordonwow** [comment]
I'm having trouble reproducing this issue. Could you send me your `BigDebuffs.lua` that's located in your SavedVariables folder?

**Comment by lvxku** [comment]
This is my setup (git won't allow a *.lua upload directly):
[BigDebuffs.zip](https://github.com/jordonwow/bigdebuffs/files/10938234/BigDebuffs.zip)

**Comment by citna** [comment]
I can replicate this happening on 11.17 and I do see it on streamer's UIs on the latest version. When testing with forced custom sizes, I can make the Polymorph appear smaller but I cannot get it to be the same size as say Ring of Frost (another dispellable CC) while being affected by both.
I think it has to do with Polymorph having the BossAura flag ( https://www.wowhead.com/spell=118/polymorph ).

**Comment by Huf12** [comment]
I have set dispellable debuffs to 95% which fits my raid frames perfecty. Any dispellable debuff besides polymorph shows with the full size. Polymorph for some reason shows a smaller icon

**Comment by jordonwow** [comment]
Thanks for the info, I think this should be fixed. @citna you were right, I wonder why they added that flag to polymorph.

**Comment by citna** [comment]
Glad I could help. Yeah, it doesn't make a lot of sense and Polymorphs (Mass Polymorph included) seemed to be the only IDs with the flag that I noticed scanning multiple spells. I figured maybe other dispellable CC from Vanilla may share the flag but didn't find any in the addon.
