### ISSUE TITLE
unstable affliction and vampiric touch not showing on wrath

### ISSUE THREAD

**Issue by Somatics23** [jordonwow/bigdebuffs#627]
hello, i have the warning debuffs 'unstable affliction' and 'vampiric touch' enabled on wrath and i don't have any of my debuff size settings at 0% and they both don't show up on raid frames in wrath classic.

**Comment by augalicious** [comment]
I'm having the same issue. I think you need to add the new spell IDs to the BigDebuffs_Wrath lua file. Max rank VT is 48160, UA is 47843. The section where you add it is towards the top of the file: "-- Show one of these when a big debuff is displayed
addon.WarningDebuffs..."
