### ISSUE TITLE
Incorrect lockout durations

### ISSUE THREAD

**Issue by Squimbert** [jordonwow/bigdebuffs#633]
Lockout durations are incorrect since they've been reduced for patch 10.1.  For example wind shear is now a 2 second lockout but shows 3+ seconds.

**Comment by citna** [comment]
Something happened to Rebuke in a random hotfix patch. I'm now seeing Rebuke on my own Player frame when I use Rebuke on anything.  https://www.wowhead.com/spell=96231/rebuke#changelog I see it has a 2nd effect. May be a Blizzard issue.
