### ISSUE TITLE
Strata issues on unit frames

### ISSUE THREAD

**Issue by Ksdemonxs** [jordonwow/bigdebuffs#655]
Some spell(s) seem like they have low strata levels, meaning that on the unitframes, only the timer appears, the spell doesn't show.

**Comment by Marews** [comment]
please help this is very annoying

**Comment by CH1ef** [comment]
Some abilities doesn't show icons on the frames/focus etc, or the icon look is different from the usual one, like polymorph.

**Comment by Ksdemonxs** [comment]
Edit: Managed to fix it by editing a one-liner (kinda scuffed but better than not showing)
![image](https://github.com/jordonwow/bigdebuffs/assets/139394409/97f48195-74af-4f73-bfc4-cecff9cfeafb)


1. Open BigDebuffs.lua 
2. Go to line 959 "frame:SetFrameLevel(parent:GetFrameLevel())"
3. Edit it to "frame:SetFrameLevel(parent:GetFrameLevel() + 1)"

**Comment by CH1ef** [comment]
Thx, its way better than right now, i hope that will be fixed anyway in next update.

**Comment by Ksdemonxs** [comment]
Still not fixed for me ;/
