### ISSUE TITLE
Error In Classic wow

### ISSUE THREAD

**Issue by yourapple** [jordonwow/bigdebuffs#671]
5x BigDebuffs/BigDebuffs.lua:1765: attempt to index field 'raidFrames' (a nil value)
[string "@BigDebuffs/BigDebuffs.lua"]:1765: in function <BigDebuffs/BigDebuffs.lua:1755>
[string "=[C]"]: in function `CompactUnitFrame_UpdateBuffs'
[string "@FrameXML/CompactUnitFrame.lua"]:606: in function `CompactUnitFrame_UpdateAuras'
[string "@FrameXML/CompactUnitFrame.lua"]:315: in function <FrameXML/CompactUnitFrame.lua:296>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAll'
[string "@FrameXML/CompactUnitFrame.lua"]:220: in function `CompactUnitFrame_SetOptionTable'
[string "@FrameXML/CompactUnitFrame.lua"]:1492: in function `func'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:325: in function `applyFunc'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:121: in function `CompactRaidFrameContainer_ApplyToFrames'
[string "@Blizzard_CUFProfiles/Blizzard_CompactUnitFrameProfiles.lua"]:540: in function `CompactUnitFrameProfiles_ApplyProfile'
[string "@Blizzard_CUFProfiles/Blizzard_CompactUnitFrameProfiles.lua"]:176: in function `CompactUnitFrameProfiles_ApplyCurrentSettings'
[string "@FrameXML/SettingDefinitions/InterfaceOverrides.lua"]:268: in function `SetRaidProfileOption'
...
[string "@SharedXML/Settings/Blizzard_Setting.lua"]:67: in function <SharedXML/Settings/Blizzard_Setting.lua:55>
[string "=[C]"]: in function `securecallfunction'
[string "@FrameXML/SettingDefinitions/InterfaceOverrides.lua"]:230: in function <...e/FrameXML/SettingDefinitions/InterfaceOverrides.lua:228>
[string "@FrameXML/SettingDefinitions/InterfaceOverrides.lua"]:234: in function `RefreshRaidOptions'
[string "@FrameXML/SettingDefinitions/InterfaceOverrides.lua"]:283: in function <...e/FrameXML/SettingDefinitions/InterfaceOverrides.lua:279>
[string "=[C]"]: ?
[string "@SharedXML/CallbackRegistry.lua"]:178: in function <SharedXML/CallbackRegistry.lua:177>
[string "=[C]"]: ?
[string "@SharedXML/CallbackRegistry.lua"]:181: in function `TriggerEvent'
[string "@SharedXML/CvarUtil.lua"]:114: in function <SharedXML/CvarUtil.lua:106>

Locals:
frame = CompactRaidFrame1 {
 0 = <userdata>
 debuffFrames = <table> {
 }
 BigDebuffs = <table> {
 }
 maxDispelDebuffs = 3
 inUse = true
 inVehicle = false
 background = CompactRaidFrame1Background {
 }
 powerBar = CompactRaidFrame1PowerBar {
 }
 hasDispelPoison = false
 healthBar = CompactRaidFrame1HealthBar {
 }
 overAbsorbGlow = CompactRaidFrame1OverAbsorbGlow {
 }
 hasDispelDisease = false
 horizTopBorder = CompactRaidFrame1HorizTopBorder {
 }
 vertRightBorder = CompactRaidFrame1VertRightBorder {
 }
 myHealPrediction = CompactRaidFrame1MyHealPrediction {
 }
 dropDown = CompactRaidFrame1DropDown {
 }
 myHealAbsorbRightShadow = CompactRaidFrame1MyHealAbsorbRightShadow {
 }
 overHealAbsorbGlow = CompactRaidFrame1OverHealAbsorbGlow {
 }
 newUnit = true
 hasDispelMagic = false
 hasDispelCurse = false
 selectionHighlight = CompactRaidFrame1SelectionHighlight {
 }
 hideHealthBarMask = 0
 myHealAbsorbLeftShadow = CompactRaidFrame1MyHealAbsorbLeftShadow {
 }
 totalAbsorbOverlay = CompactRaidFrame1TotalAbsorbOverlay {
 }
 unit = "player"
 unitExists = true
 displayedUnit = "player"
 unusedFunc = <function> defined @Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua:46
 statusText = CompactRaidFrame1StatusText {
 }
 horizDivider = CompactRaidFrame1HorizDivider {
 }
 updateAllEvent = "GROUP_ROSTER_UPDATE"
 roleIcon = CompactRaidFrame1RoleIcon {
 }
 applyFunc = <function> defined @Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua:324
 menu = <function> defined @FrameXML/CompactUnitFrame.lua:267
 otherHealPrediction = CompactRaidFrame1OtherHealPrediction {
 }
 optionTable = <table> {
 }
 buffFrames = <table> {
 }
 centerStatusIcon = CompactRaidFrame1CenterStatusIcon {
 }
 maxDebuffs = 3
 dispelDebuffFrames = <table> {
 }
 myHealAbsorb = CompactRaidFrame1MyHealAbsorb {
 }
 maxBuffs = 3
 vertLeftBorder = CompactRaidFrame1VertLeftBorder {
 }
 horizBottomBorder = CompactRaidFrame1HorizBottomBorder {
 }
 name = CompactRaidFrame1Name {
 }
 readyCheckIcon = CompactRaidFrame1ReadyCheckIcon {
 }
 totalAbsorb = CompactRaidFrame1TotalAbsorb {
 }
}
(*temporary) = nil
(*temporary) = "player"
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'raidFrames' (a nil value)"
INCREASED_MAX_BUFFS = 6
UnitBuff = <function> defined =[C]:-1
CompactUnitFrame_UtilShouldDisplayBuff = <function> defined @BigDebuffs/BigDebuffs.lua:1628

5x BigDebuffs/BigDebuffs.lua:1910: attempt to index field 'raidFrames' (a nil value)
[string "@BigDebuffs/BigDebuffs.lua"]:1910: in function `ShowBigDebuffs'
[string "@BigDebuffs/BigDebuffs.lua"]:1751: in function <BigDebuffs/BigDebuffs.lua:1658>
[string "=[C]"]: in function `CompactUnitFrame_UpdateDebuffs'
[string "@FrameXML/CompactUnitFrame.lua"]:607: in function `CompactUnitFrame_UpdateAuras'
[string "@FrameXML/CompactUnitFrame.lua"]:315: in function <FrameXML/CompactUnitFrame.lua:296>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAll'
[string "@FrameXML/CompactUnitFrame.lua"]:220: in function `CompactUnitFrame_SetOptionTable'
[string "@FrameXML/CompactUnitFrame.lua"]:1492: in function `func'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:325: in function `applyFunc'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:121: in function `CompactRaidFrameContainer_ApplyToFrames'
[string "@Blizzard_CUFProfiles/Blizzard_CompactUnitFrameProfiles.lua"]:540: in function `CompactUnitFrameProfiles_ApplyProfile'
[string "@Blizzard_CUFProfiles/Blizzard_CompactUnitFrameProfiles.lua"]:176: in function `CompactUnitFrameProfiles_ApplyCurrentSettings'
...
[string "@SharedXML/Settings/Blizzard_Setting.lua"]:67: in function <SharedXML/Settings/Blizzard_Setting.lua:55>
[string "=[C]"]: in function `securecallfunction'
[string "@FrameXML/SettingDefinitions/InterfaceOverrides.lua"]:230: in function <...e/FrameXML/SettingDefinitions/InterfaceOverrides.lua:228>
[string "@FrameXML/SettingDefinitions/InterfaceOverrides.lua"]:234: in function `RefreshRaidOptions'
[string "@FrameXML/SettingDefinitions/InterfaceOverrides.lua"]:283: in function <...e/FrameXML/SettingDefinitions/InterfaceOverrides.lua:279>
[string "=[C]"]: ?
[string "@SharedXML/CallbackRegistry.lua"]:178: in function <SharedXML/CallbackRegistry.lua:177>
[string "=[C]"]: ?
[string "@SharedXML/CallbackRegistry.lua"]:181: in function `TriggerEvent'
[string "@SharedXML/CvarUtil.lua"]:114: in function <SharedXML/CvarUtil.lua:106>

Locals:
self = <table> {
 NAME_PLATE_UNIT_REMOVED = <function> defined @BigDebuffs/BigDebuffs.lua:2372
 SetDefaultModuleLibraries = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 SaveUnitFramePosition = <function> defined @BigDebuffs/BigDebuffs.lua:1096
 EnableModule = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 baseName = "BigDebuffs"
 dispelTypes = <table> {
 }
 IsDispellable = <function> defined @BigDebuffs/BigDebuffs.lua:1377
 SecureHookScript = <function> defined @AdiBags/libs/AceHook-3.0/AceHook-3.0.lua:409
 IsPriorityBigDebuff = <function> defined @BigDebuffs/BigDebuffs.lua:2028
 IsPriorityDebuff = <function> defined @BigDebuffs/BigDebuffs.lua:1367
 PriorityDebuffs = <table> {
 }
 SetDefaultModulePrototype = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 defaultModuleState = true
 IsEnabled = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 DisableModule = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:346
 RegisterMessage = <function> defined @Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 frames = <table> {
 }
 hooks = <table> {
 }
 PLAYER_FOCUS_CHANGED = <function> defined @BigDebuffs/BigDebuffs.lua:2292
 WarningDebuffs = <table> {
 }
 UNIT_AURA = <function> defined @BigDebuffs/BigDebuffs.lua:2034
 SetEnabledState = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @AdiBags/libs/AceHook-3.0/AceHook-3.0.lua:273
 enabledState = true
 COMBAT_LOG_EVENT_UNFILTERED = <function> defined @BigDebuffs/BigDebuffs.lua:1170
 RegisterEvent = <function> defined @Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 units = <table> {
 }
 IterateModules = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:433
 AttachNameplate = <function> defined @BigDebuffs/BigDebuffs.lua:1051
 RawHook = <function> defined @AdiBags/libs/AceHook-3.0/AceHook-3.0.lua:312
 AttachUnitFrame = <function> defined @BigDebuffs/BigDebuffs.lua:887
 UNIT_AURA_NAMEPLATE = <function> defined @BigDebuffs/BigDebuffs.lua:2170
 OnInitialize = <function> defined @BigDebuffs/BigDebuffs.lua:786
 NewModule = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 GetModule = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:206
 AttachedFrames = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 options = <table> {
 }
 Spells = <table> {
 }
 GetName = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 UNIT_AURA_ALL_UNITS = <function> defined @BigDebuffs/BigDebuffs.lua:1243
 name = "BigDebuffs"
 GetNameplatesPriority = <function> defined @BigDebuffs/BigDebuffs.lua:1466
 orderedModules = <table> {
 }
 Nameplates = <table> {
 }
 Disable = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 ShowInRaids = <function> defined @BigDebuffs/BigDebuffs.lua:2389
 anchors = <table> {
 }
 db = <table> {
 }
 SetupOptions = <function> defined @BigDebuffs/Options.lua:230
 NAME_PLATE_UNIT_ADDED = <function> defined @BigDebuffs/BigDebuffs.lua:2304
 HookScript = <function> defined @AdiBags/libs/AceHook-3.0/AceHook-3.0.lua:365
 UNIT_PET = <function> defined @BigDebuffs/BigDebuffs.lua:2300
 GetAuraPriority = <function> defined @BigDebuffs/BigDebuffs.lua:1443
 ShowBigDebuffs = <function> defined @BigDebuffs/Big

**Comment by Xaero252** [comment]
Open the bigdebuffs settings, change a setting in the "Raid Frames" section and then /reload. Fixed it for me.
