### ISSUE TITLE
[Classic WoW] lua error

### ISSUE THREAD

**Issue by waytoomuchgaming** [jordonwow/bigdebuffs#672]
5x BigDebuffs/BigDebuffs.lua:1910: attempt to index field 'raidFrames' (a nil value)
[string "@BigDebuffs/BigDebuffs.lua"]:1910: in function `ShowBigDebuffs'
[string "@BigDebuffs/BigDebuffs.lua"]:1751: in function <BigDebuffs/BigDebuffs.lua:1658>
[string "=[C]"]: in function `CompactUnitFrame_UpdateDebuffs'
[string "@FrameXML/CompactUnitFrame.lua"]:607: in function `CompactUnitFrame_UpdateAuras'
[string "@FrameXML/CompactUnitFrame.lua"]:315: in function <FrameXML/CompactUnitFrame.lua:296>
[string "=[C]"]: ?
[string "=[C]"]: in function `CompactUnitFrame_UpdateAll'
[string "@FrameXML/CompactUnitFrame.lua"]:220: in function `CompactUnitFrame_SetOptionTable'
[string "@FrameXML/CompactUnitFrame.lua"]:1492: in function <FrameXML/CompactUnitFrame.lua:1340>
[string "=[C]"]: in function `func'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:325: in function `applyFunc'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:121: in function `CompactRaidFrameContainer_ApplyToFrames'
...
[string "@SharedXML/CallbackRegistry.lua"]:178: in function <SharedXML/CallbackRegistry.lua:177>
[string "=[C]"]: ?
[string "@SharedXML/CallbackRegistry.lua"]:181: in function `TriggerEvent'
[string "@SharedXML/CvarUtil.lua"]:114: in function <SharedXML/CvarUtil.lua:106>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetCVar'
[string "@SharedXML/ClassicCvarUtil.lua"]:7: in function <SharedXML/ClassicCvarUtil.lua:3>
[string "=[C]"]: in function `SetCVar'
[string "@ClassicPlatesPlus/core.lua"]:76: in function `CVars'
[string "@ClassicPlatesPlus/init.lua"]:56: in function <ClassicPlatesPlus/init.lua:11>

Locals:
self = <table> {
 NAME_PLATE_UNIT_REMOVED = <function> defined @BigDebuffs/BigDebuffs.lua:2372
 SetDefaultModuleLibraries = <function> defined @Baggins/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 SaveUnitFramePosition = <function> defined @BigDebuffs/BigDebuffs.lua:1096
 EnableModule = <function> defined @Baggins/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 baseName = "BigDebuffs"
 dispelTypes = <table> {
 }
 IsDispellable = <function> defined @BigDebuffs/BigDebuffs.lua:1377
 SecureHookScript = <function> defined @Baggins/Libs/AceHook-3.0/AceHook-3.0.lua:409
 IsPriorityBigDebuff = <function> defined @BigDebuffs/BigDebuffs.lua:2028
 IsPriorityDebuff = <function> defined @BigDebuffs/BigDebuffs.lua:1367
 PriorityDebuffs = <table> {
 }
 SetDefaultModulePrototype = <function> defined @Baggins/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 defaultModuleState = true
 IsEnabled = <function> defined @Baggins/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 DisableModule = <function> defined @Baggins/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 RegisterMessage = <function> defined @Baggins/Libs/CallBackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Baggins/Libs/CallBackHandler-1.0/CallbackHandler-1.0.lua:143
 frames = <table> {
 }
 hooks = <table> {
 }
 PLAYER_FOCUS_CHANGED = <function> defined @BigDebuffs/BigDebuffs.lua:2292
 WarningDebuffs = <table> {
 }
 UNIT_AURA = <function> defined @BigDebuffs/BigDebuffs.lua:2034
 SetEnabledState = <function> defined @Baggins/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Baggins/Libs/AceHook-3.0/AceHook-3.0.lua:273
 enabledState = true
 COMBAT_LOG_EVENT_UNFILTERED = <function> defined @BigDebuffs/BigDebuffs.lua:1170
 RegisterEvent = <function> defined @Baggins/Libs/CallBackHandler-1.0/CallbackHandler-1.0.lua:80
 units = <table> {
 }
 IterateModules = <function> defined @Baggins/Libs/AceAddon-3.0/AceAddon-3.0.lua:433
 AttachNameplate = <function> defined @BigDebuffs/BigDebuffs.lua:1051
 RawHook = <function> defined @Baggins/Libs/AceHook-3.0/AceHook-3.0.lua:312
 AttachUnitFrame = <function> defined @BigDebuffs/BigDebuffs.lua:887
 UNIT_AURA_NAMEPLATE = <function> defined @BigDebuffs/BigDebuffs.lua:2170
 OnInitialize = <function> defined @BigDebuffs/BigDebuffs.lua:786
 NewModule = <function> defined @Baggins/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 GetModule = <function> defined @Baggins/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 AttachedFrames = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 options = <table> {
 }
 Spells = <table> {
 }
 GetName = <function> defined @Baggins/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 UNIT_AURA_ALL_UNITS = <function> defined @BigDebuffs/BigDebuffs.lua:1243
 name = "BigDebuffs"
 GetNameplatesPriority = <function> defined @BigDebuffs/BigDebuffs.lua:1466
 orderedModules = <table> {
 }
 Nameplates = <table> {
 }
 Disable = <function> defined @Baggins/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 ShowInRaids = <function> defined @BigDebuffs/BigDebuffs.lua:2389
 anchors = <table> {
 }
 db = <table> {
 }
 SetupOptions = <function> defined @BigDebuffs/Options.lua:230
 NAME_PLATE_UNIT_ADDED = <function> defined @BigDebuffs/BigDebuffs.lua:2304
 HookScript = <function> defined @Baggins/Libs/AceHook-3.0/AceHook-3.0.lua:365
 UNIT_PET = <function> defined @BigDebuffs/BigDebuffs.lua:2300
 GetAuraPriority = <function> defined @BigDebuffs/BigDebuffs.lua:1443
 ShowBigDebuffs = <function> defined @BigDebuf

**Comment by Xaero252** [comment]
Open the bigdebuffs settings, change a setting in the "Raid Frames" section and then /reload. Fixed it for me.
