### ISSUE TITLE
Bleed Dispell

### ISSUE THREAD

**Issue by Antorinia** [jordonwow/bigdebuffs#678]
hey hey, can you add bleed dispell for evokers pls?

Bleed = function() return IsUsableSpell(GetSpellInfo(374251)) end

**Comment by Antorinia** [comment]
also, one more questions, you have size for regular buffs, is it possible to add size for regular debuffs also?
![image](https://github.com/jordonwow/bigdebuffs/assets/130331287/fdf777dc-426b-4fa1-b8e4-1e6a57d8508c)

**Comment by jordonwow** [comment]
Yes, I will look into this

**Comment by Antorinia** [comment]
ty!
