### ISSUE TITLE
BigDebuffs Bug Cata 5/15

### ISSUE THREAD

**Issue by SleekSnake** [jordonwow/bigdebuffs#725]
1x [string "*BigDebuffs.xml:23_OnEnter"]:3: Invalid spell ID in GameTooltip:SetSpellByID
[string "=[C]"]: in function `SetSpellByID'
[string "*BigDebuffs.xml:23_OnEnter"]:3: in function <[string "*BigDebuffs.xml:23_OnEnter"]:1>

**Comment by stako** [comment]
This happens because [this line](https://github.com/jordonwow/bigdebuffs/blob/0490ce0274e8a13b5b3aeb77ce030600f827a107/BigDebuffs.lua#L2015) adds an entry to the debuffs table that includes a boolean where a spell ID is expected.

The `true` should be changed to `warningId`
