### ISSUE TITLE
fontsize slider on raidframes not working (retail)

### ISSUE THREAD

**Issue by mehhxyeah** [jordonwow/bigdebuffs#760]
Its been almost 2 years, since dragonflight beta version, where the slider adjusting the fontsize on raidframes does not work (you can move the slider and adjust the values but the it doesn not get applied on the debuffs on the raidframe).
I dont know how hard it is to fix, but for me its kinda breaking, had to use the dragonflight beta version throughout the whole xpansion because of this

**Comment by mehhxyeah** [comment]
apparently this should be the fix https://media.discordapp.net/attachments/560505711088500737/1266011557993648150/image.png?ex=66a398a4&is=66a24724&hm=46effaaeb4770097773d9accd39c9a994ee5253fbe4d5e5a4c041860995812c6&=&format=webp&quality=lossless
lines 1348 & 49

**Comment by jordonwow** [comment]
Thanks for the patch
