### ISSUE TITLE
broken on today patch 

### ISSUE THREAD

**Issue by memo0704** [jordonwow/bigdebuffs#765]
Addon broken on today patch 11.0.2

**Comment by farske** [comment]
194x BigDebuffs/BigDebuffs.lua:1691: Usage: SpellGetVisibilityInfo(spellID, "visType")
[string "=[C]"]: in function `SpellGetVisibilityInfo'
[string "@BigDebuffs/BigDebuffs.lua"]:1691: in function <BigDebuffs/BigDebuffs.lua:1688>
[string "@BigDebuffs/BigDebuffs.lua"]:1776: in function <BigDebuffs/BigDebuffs.lua:1702>
[string "=[C]"]: in function `CompactUnitFrame_UpdateDebuffs'
[string "@Blizzard_UnitFrame/Classic/CompactUnitFrame.lua"]:607: in function `CompactUnitFrame_UpdateAuras'
[string "@Blizzard_UnitFrame/Classic/CompactUnitFrame.lua"]:106: in function <...dOns/Blizzard_UnitFrame/Classic/CompactUnitFrame.lua:59>

Locals:
(*temporary) = nil
(*temporary) = "RAID_INCOMBAT

**Comment by stako** [comment]
`spellId` is nil because the `UnitDebuff` call is returning a single object - a table. Looks like the `UnitDebuffTest` function is being substituted in.

**Comment by jordonwow** [comment]
Thanks
