### ISSUE TITLE
App Config Issues (Fails to start)

### ISSUE THREAD

**Issue by Lottey0710** [jordonwow/bigdebuffs#766]
Addon will not launch fails to config, below is my buggrabber 

224x BigDebuffs/BigDebuffs.lua:2212: attempt to call local 'UnitDebuff' (a nil value)
[string "@BigDebuffs/BigDebuffs.lua"]:2212: in function `UNIT_AURA_NAMEPLATE'
[string "@BigDebuffs/BigDebuffs.lua"]:2394: in function `?'
[string "@BigDebuffs/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ffs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@BigDebuffs/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ffs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@BigDebuffs/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@BigDebuffs/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <BigDebuffs/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 HiddenDebuffs = <table> {
 }
 modules = <table> {
 }
 baseName = "BigDebuffs"
 PriorityDebuffs = <table> {
 }
 defaultModuleState = true
 frames = <table> {
 }
 hooks = <table> {
 }
 WarningDebuffs = <table> {
 }
 enabledState = true
 units = <table> {
 }
 AttachedFrames = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 specDispel = <table> {
 }
 Spells = <table> {
 }
 name = "BigDebuffs"
 specDispelTypes = <table> {
 }
 Nameplates = <table> {
 }
 UnitFrames = <table> {
 }
 db = <table> {
 }
 orderedModules = <table> {
 }
 anchors = <table> {
 }
}
unit = "nameplate1"
frame = NamePlate1PlaterUnitFrame.BigDebuffs {
 anchor = NamePlate1PlaterUnitFrameHealthBar {
 }
 icon = NamePlate1PlaterUnitFrame.BigDebuffs.Icon {
 }
 cooldown = NamePlate1PlaterUnitFrame.BigDebuffs.Cooldown {
 }
 unit = "nameplate1"
}
UnitDebuff = nil
now = 641895.107000
left = 0
priority = 0
duration = nil
expires = nil
icon = nil
debuff = nil
buff = nil
interrupt = nil
(for index) = 1
(for limit) = 40
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = "nameplate1"
(*temporary) = 1
(*temporary) = "attempt to call local 'UnitDebuff' (a nil value)"
UnitDebuff = nil
LibClassicDurations = false
UnitBuff = nil

**Comment by jordonwow** [comment]
Is this occurring on the latest version?

**Comment by Lottey0710** [comment]
Yes. I installed the previous launch as well. One additional note is this is a fresh install of the addon on new PC in case it's an initialization issue. Happy to provide more information as needed.

Thanks for all you do

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jordonwow** [comment]
It looks like you still have v30 installed (the line numbers of your error matches that version). Latest version (v32) should resolve that for you.
