### ISSUE TITLE
Buffs not showing with ElvUI player frame

### ISSUE THREAD

**Issue by TheOmegaOne** [jordonwow/bigdebuffs#781]
I've tried resetting my player frame to elv UI default to no success, also copying the settings from the elvui target & focus frames - which do work to no success. Turning off elv UI then big debuffs is working with the blizzard default player frame, so it's likely an interaction specifically with Elv UI which is no longer working.

**Comment by TheOmegaOne** [comment]
if unit:match("player") then
		local elvUIFrame = _G["ElvUF_Player"]
		if elvUIFrame and elvUIFrame:IsVisible() and elvUIFrame.unit then
			if unitGUID == UnitGUID(elvUIFrame.unit) then
				return elvUIFrame
			end
		end
	    end
	    
I fixed it locally by adding this code inside the "if unit and (unit:match("party") or unit:match("player")) then" block - as this block seems to only be returning party frames despite also checking if the matched unit is the player.

**Comment by dumbrellas** [comment]
Thanks this worked for me as well

**Comment by Zaoza7** [comment]
I'm pretty hopeless with codes. Where in the LUa file do I enter that code? And does it replace something or is it an addition?

**Comment by Tenoke** [comment]
> ```
>     if unit:match("player") then
> 	local elvUIFrame = _G["ElvUF_Player"]
> 	if elvUIFrame and elvUIFrame:IsVisible() and elvUIFrame.unit then
> 		if unitGUID == UnitGUID(elvUIFrame.unit) then
> 			return elvUIFrame
> 		end
> 	end
>     end
> ```
> 
> I fixed it locally by adding this code inside the "if unit and (unit:match("party") or unit:match("player")) then" block - as this block seems to only be returning party frames despite also checking if the matched unit is the player.

Is Bigdebufss no longer under development that we need to edit it manually? Can you send it as a PR if they accept them?

**Comment by jordonwow** [comment]
I added your patch, thanks for the report.
