### ISSUE TITLE
Square on portraits

### ISSUE THREAD

**Issue by HuMa69** [jordonwow/bigdebuffs#786]
when someone has a buff or CC there is a hugly square instead attaching to the rounded portrait, i put screenshot 
![Captura](https://github.com/user-attachments/assets/92d801a8-b65d-4fe4-bbc0-86184ebb69f9)

This is on cata.

**Comment by HuMa69** [comment]
NVM i fixed it, this was caused by masque, i just turned off the global profile of masque and only enable the bartender

**Comment by mektrix** [comment]
Have this issue with no other addons enabled
![Screenshot 2024-09-10 103208](https://github.com/user-attachments/assets/19b735ee-3ae3-4eb9-aac0-808bc78c207a)
