### ISSUE TITLE
Lua Error when using mouseover macro on player frame

### ISSUE THREAD

**Issue by Oreo-hhh** [jordonwow/bigdebuffs#87]
This error pops up when using my renew and power word: shield mouseover macro on my player frame. Same as ticket #74. In the last build, I was able to reproduce it 100% but now its like 50% or so. Love the add on. Thank you for taking the time to fix this.

Message: Interface\FrameXML\CompactUnitFrame.lua:1023: attempt to index local 'buffFrame' (a nil value)
Time: Thu Jun 18 06:11:17 2020
Count: 7
Stack: Interface\FrameXML\CompactUnitFrame.lua:1023: attempt to index local 'buffFrame' (a nil value)
Interface\FrameXML\CompactUnitFrame.lua:1023: in function <Interface\FrameXML\CompactUnitFrame.lua:1021>
[C]: ?
[C]: in function `CompactUnitFrame_UtilSetBuff'
Interface\AddOns\BigDebuffs\BigDebuffs.lua:1246: in function <Interface\AddOns\BigDebuffs\BigDebuffs.lua:1220>
[C]: in function `CompactUnitFrame_UpdateBuffs'
Interface\FrameXML\CompactUnitFrame.lua:552: in function `CompactUnitFrame_UpdateAuras'
Interface\FrameXML\CompactUnitFrame.lua:98: in function <Interface\FrameXML\CompactUnitFrame.lua:51>

Locals: buffFrame = nil
unit = "player"
index = 6
filter = nil
name = "Renew"
icon = 135953
count = 0
debuffType = "Magic"
duration = 15
expirationTime = 459830.621000
unitCaster = "player"
canStealOrPurge = false
_ = false
spellId = 10929
canApplyAura = true
(*temporary) = false
(*temporary) = false
(*temporary) = 10929
(*temporary) = true
(*temporary) = "attempt to index local 'buffFrame' (a nil value)"

Message: Interface\FrameXML\CompactUnitFrame.lua:1023: attempt to index local 'buffFrame' (a nil value)
Time: Thu Jun 18 06:21:21 2020
Count: 11
Stack: Interface\FrameXML\CompactUnitFrame.lua:1023: attempt to index local 'buffFrame' (a nil value)
Interface\FrameXML\CompactUnitFrame.lua:1023: in function <Interface\FrameXML\CompactUnitFrame.lua:1021>
[C]: ?
[C]: in function `CompactUnitFrame_UtilSetBuff'
Interface\AddOns\BigDebuffs\BigDebuffs.lua:1246: in function <Interface\AddOns\BigDebuffs\BigDebuffs.lua:1220>
[C]: in function `CompactUnitFrame_UpdateBuffs'
Interface\FrameXML\CompactUnitFrame.lua:552: in function `CompactUnitFrame_UpdateAuras'
Interface\FrameXML\CompactUnitFrame.lua:98: in function <Interface\FrameXML\CompactUnitFrame.lua:51>

Locals: buffFrame = nil
unit = "player"
index = 4
filter = nil
name = "Power Word: Shield"
icon = 135940
count = 0
debuffType = "Magic"
duration = 30
expirationTime = 460451.309000
unitCaster = "player"
canStealOrPurge = false
_ = false
spellId = 10901
canApplyAura = true
(*temporary) = false
(*temporary) = false
(*temporary) = 10901
(*temporary) = true
(*temporary) = "attempt to index local 'buffFrame' (a nil value)"

**Comment by jordonwow** [comment]
Fixed, thank you for the report!
