### ISSUE TITLE
Please add Gladiator's Maledict Trinket

### ISSUE THREAD

**Issue by ShitshowJoe** [jordonwow/bigdebuffs#9]
I'm having a hard time getting the addon to let me see when my team is affected by the Gladiator's Maledict trinket. If I make it so it shows all debuffs, even when BigDebuffs is displaying, I have to increase the maximum debuffs to 5+ and the effect usually is drowned out by poisons/diseases and such. Love your addon, and if I could figure out how to add spells through the interface/lua file I would totally do this myself!

**Comment by Admoney70** [comment]
[294127] = { type = "cc" }, -- Maledict

I could upload my LUA file but it has a few more custom edits you may not want...
fixed vendetta, added touch of death and some others i can think of

**Comment by jordonwow** [comment]
Added (#14)
